### ISSUE TITLE
NotifyConfirm API order

### ISSUE THREAD

**Issue by streadway** [streadway/amqp#112]
In all practical cases, publisher Acks and Nacks should maintain the same sequence as publishings.

The current API of using two channels and a `select {}` over them leaves the ordering to the whim of the runtime scheduler.

Two options for how to handle this:

1. Remove the order guarantee from the library and leave that as an implementation complexity of the client.  The sequences will still be interpolated for `n/ack{multiple=true}`.

2. Change the interface of NotifyConfirm to instead accept a single chan of `type Confirmation struct { Id int64, Nack bool }` instead of two chans and maintain the strict ordering against the published sequence.

Please discuss.

**Comment by streadway** [comment]
@gaffneyc it's been a while, but I've put 3eba494 together as an example of how a single chan of publisher confirmations could work.  Would you please take a look?

This addresses requiring the application to maintain state from the Publish calls by ensuring strict ordering of acks/nacks.  I can't think of an example where delivering out-of-sequence DeliveryTags would be interesting for users of this library.

**Comment by streadway** [comment]
@michaelklishin can you think of a reason where consuming out-of-order confirmations would be desirable behavior?

**Comment by gaffneyc** [comment]
It looks pretty good. We [ended up with something similar](https://gist.github.com/gaffneyc/5cfff36dfcbd2c9c48d7) on a client wrapper we're hoping to open source at some point. I'll give the changes a try on one of our apps here in the next day or two.

The `confirms` struct doesn't look to be thread safe but I'm not sure if it needs to be or not.

**Comment by streadway** [comment]
Good find.  A -race check confirms that `Channel.dispatch` and `Channel.Publish` are not properly ordered.  Instead of holding `Channel.m` in `Channel.dispatch`, it makes more sense to make `confirms` thread safe.  Fixed in the confirmations branch.

**Comment by gaffneyc** [comment]
I finally had a chance to test out the changes locally and they are looking good so far. I posted a comment on the confirms code around ordering that I'm curious about. Mainly trying to understand the semantics so we I know we're not missing and acknowledgements.
