### ISSUE TITLE
Use tag to release version

### ISSUE THREAD

**Issue by guilhem** [streadway/amqp#125]
Even if golang hasn't any notion of "version" for a lib, we can use some external tool to manage dependencies versions.
For example we are using https://github.com/gpmgo/gopm .
With tags, we can be able to have the same behavior between any build machine at any time.

**Comment by sagikazarmark** [comment]
Is there any chance to revise this decision? There are package managers for Go (godep, glide, etc) and there is one (dep) which is going to be the official one.

**Comment by michaelklishin** [comment]
@sagikazarmark it's been discussed more than once since Dec 2014. Things will stay as they are in the short term. I personally think that using branches for release series and tags would be better.
Maybe once Go adopts an official package management tool, this can be revisited.

**Comment by Southclaws** [comment]
I really think this should be reopened and reconsidered soon, [as Sam Boyer mentions](https://www.youtube.com/watch?v=5LtMb090AZI) `dep` is production ready and is on the road to be implemented into the Go toolchain so it's a good time to start migrating to a version system.

Yes revision SHA1's are an acceptable workaround but semver just makes more sense, is easy to distinguish newer from older and is simply just prettier!

**Comment by pierrre** [comment]
Hello!
Any plan to add a release tag ?
