### ISSUE TITLE
Example for prefetch count

### ISSUE THREAD

**Issue by s888** [streadway/amqp#131]
Is there an example that demonstrates RabbitMQ's prefetch count ? I am not able to find it.

**Comment by streadway** [comment]
This blog post has some good examples of how to tune prefetch: https://www.rabbitmq.com/blog/2014/04/03/an-end-to-synchrony-performance-improvements-in-3-3/

When it comes to this API, the basic.qos method is a per-channel method which is implemented as [`Channel.Qos`](http://godoc.org/github.com/streadway/amqp#Channel.Qos).

**Comment by s888** [comment]
@streadway thanks :)
