### ISSUE TITLE
Channel closed due to 404 when ExchangeDeclarePassive

### ISSUE THREAD

**Issue by mikechack** [streadway/amqp#132]
I understand that the documentation clearly states that a Channel is closed when an error is returned. Seems a little excessive in the case of a DeclarePassive in that one is trying to test for existence. In my use case I am waiting for a server side process to create an exchange and am looping and testing and creating a new channel as a result of testing for existence doesn't make sense.

**Comment by michaelklishin** [comment]
@mikechack this is how the server works. It closes the channel on any channel exception. Use a one-off channel.

**Comment by streadway** [comment]
Yup, there is not much that this client can do as it's expected behavior.
