### ISSUE TITLE
Unlimited timeout

### ISSUE THREAD

**Issue by andygrunwald** [streadway/amqp#135]
You had provided an example for setting a custom timeout. See http://godoc.org/github.com/streadway/amqp#example-Config--Timeout. 
And of course for reconnect also. See https://github.com/streadway/amqp/blob/master/reconnect_test.go
Thanks for this!

Is there a possibility to apply unlimited timeout? To set timeout to 0 or -x?
Or do i have to deal with reconnects?

**Comment by michaelklishin** [comment]
You have to deal with re-connects regardless of the timeout.

Infinite timeouts is a terrible idea. Use a very high value (e.g. one minute) if you really want to.

**Comment by andygrunwald** [comment]
Thanks :)
Than i will have some coding session tonight ;)
