### ISSUE TITLE
panic: negative bit index

### ISSUE THREAD

**Issue by OSadovy** [streadway/amqp#136]
we're eventually getting following panic on prod, which I currently can not reproduce:

panic: negative bit index

goroutine 8 [running]:
math/big.(*Int).SetBit(0xc20811a1c0, 0xc20811a1c0, 0xffffffffffffffff, 0x0, 0xb9b410)
	/usr/local/go/src/math/big/int.go:819 +0x8a
github.com/streadway/amqp.(*allocator).release(0xc20811a1e0, 0x0)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/allocator.go:105 +0x4d
github.com/streadway/amqp.(*Connection).releaseChannel(0xc2080cd0e0, 0xc208c50000)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:558 +0xb7
github.com/streadway/amqp.(*Connection).closeChannel(0xc2080cd0e0, 0xc20a1c9b80, 0xc208c55e00)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:579 +0x4f
github.com/streadway/amqp.func·002()
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:348 +0x169
sync.(*Once).Do(0xc2080cd0e0, 0xc20824cdb8)
	/usr/local/go/src/sync/once.go:44 +0xd4
github.com/streadway/amqp.(*Connection).shutdown(0xc2080cd0e0, 0xc208c55e00)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:368 +0x58
github.com/streadway/amqp.(*Connection).dispatch0(0xc2080cd0e0, 0x7fe0911ada30, 0xc208c55da0)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:392 +0x3b2
github.com/streadway/amqp.(*Connection).demux(0xc2080cd0e0, 0x7fe0911ada30, 0xc208c55da0)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:375 +0x5c
github.com/streadway/amqp.(*Connection).reader(0xc2080cd0e0, 0x7fe0911ad6d8, 0xc208038088)
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:469 +0x211
created by github.com/streadway/amqp.Open
	/opt/buildAgent/work/e6c5857f86a095df/vendor/src/github.com/streadway/amqp/connection.go:218 +0x389

It seems library tries to release channel with id 0 as part of connection shutdown process which for some reason goes through ID allocator (0 -1 = -1, oops).

**Comment by domashevskiy** [comment]
Sample code to reproduce.
```go
import (
    "sync"
    "log"
    "runtime"
    "github.com/streadway/amqp"
)

func init() {
	runtime.GOMAXPROCS(runtime.NumCPU())
}

func createChannels(conn *amqp.Connection, wg *sync.WaitGroup) {
	for i := 0; i < 10000; i++ {
		ch, err := conn.Channel()
		if err != nil {
			panic(err)
		}
		ch.Close()
	}
	wg.Done()
}

func channels() {
	conn, err := amqp.Dial("amqp://domash:domash@localhost:5672/")
	if err != nil {
		log.Fatalf("connection.open: %s", err)
	}
	defer conn.Close()

	wg := new(sync.WaitGroup)

	for i := 0; i < 8; i++ {
		wg.Add(1)
		go createChannels(conn, wg)
	}
	wg.Wait()
}

func main() {
	channels()
}

```
