### ISSUE TITLE
channel.go confimOne() index out of range

### ISSUE THREAD

**Issue by bluntelk** [streadway/amqp#140]
Hi There,

I ran across an issue today where confimOne() in channel.go (line 568) would try and pop an empty confirms heap. this caused an index out of range panic.

I inserted the following code snippet at line 577 (so just inside the for loop) and the problem was solved.

```
        if me.confirms.Len() == 0 {
            break;
        }
```

Just wanting to know - am I doing this the right way?

The code that will fail _every_ time is located here: 
https://bitbucket.org/swiftnetworks/sensu-client/branch/mq-change

All I am doing is trying to make the publishing of results reliable.

**Comment by streadway** [comment]
Hi @bluntelk 

I just pushed https://github.com/streadway/amqp/commit/33324439e3b9a0ae70e1a0bf4741bec1ec94c9c6 which should make reliable publishing simpler by using `NotifyPublish` instead of `NotifyConfirm`.

Would you please test to see if you can reproduce this issue?

**Comment by michaelklishin** [comment]
Closing as over 1 year old without a response.
