### ISSUE TITLE
amqp.Dial failed to pass the string with %

### ISSUE THREAD

**Issue by opiuman** [streadway/amqp#142]
parse amqp://test:test%t@localhost:8080: invalid URL escape "%ev"

**Comment by michaelklishin** [comment]
See https://en.wikipedia.org/wiki/Percent-encoding. Some URI parts are expected [by RabbitMQ clients] to be percent-encoded.

**Comment by wilbeibi** [comment]
Meet same issue. Rabbitmq management UI do accepts non percent-encoding characters.

**Comment by Ydcool** [comment]
This is a bit of counter-intuitive. I think the url should be detected and encoded before parseURI in DialConfig.
