### ISSUE TITLE
NotifyClose usage is a bit unclear

### ISSUE THREAD

**Issue by nopejpg** [streadway/amqp#148]
I've been doing some testing with a consumer by `kill -9` my rabbitmq server. During this process the consumers channel/connection dies (duh!); the problem is that when I start up rabbitmq the channel and connection are not smart enough to detect and recover from the error. I thought that `NotifyClose` was the solution but it doesn't seem to be?

Also, probably a feature request, but if I could check the connection/channel with `Closed() bool` it'd be easier to pool connections and recover from the issue mentioned above.

**Comment by kron4eg** [comment]
>the problem is that when I start up rabbitmq the channel and connection are not smart enough to detect and recover from the error.

They are dead objects after disconnect, you should run connect/obtain channel/declare one more time. This library doesn't do reconnection/recovery at all (and should not).

`NotifyClose()` will tell you 1 time that connection/channel is closed, everything else you should do my hands.

> check the connection/channel with Closed() bool

There is not point in this, you should utilise `(*Connection).NotifyClose()` to know what's the state of connection.

>pool connections

No, you don't want this :) Always use only 1 connection and many channels inside.

**Comment by nopejpg** [comment]
@kron4eg yea I figured that out the hard way ;) thanks though!

**Comment by kron4eg** [comment]
@nopejpg btw, I've wrote little high-level wrapper around this lib, to avoid doing reconnect logic every time: https://github.com/assembla/cony
