### ISSUE TITLE
Listing all queues

### ISSUE THREAD

**Issue by katcipis** [streadway/amqp#153]
Is there a way to list all the queues ? Like:

```
rabbitmqadmin list queues name
```

**Comment by zbentley** [comment]
Likely not in this library. You could either shell out and run that function yourself, or use the [RabbitMQ management API](https://www.rabbitmq.com/management.html). The HTTP API is simple, and could be addressed directly, e.g. via `curl`, or via an API client library in your language of choice. One or more are available for Go; I have used https://github.com/michaelklishin/rabbit-hole, and it works quite well.

**Comment by michaelklishin** [comment]
There is no operation for queue listing in the protocol. So yes, use the HTTP API which is primarily developed for operations. `rabbit-hole` is a Go client for it.
