### ISSUE TITLE
Parse int error when trying to connect with password

### ISSUE THREAD

**Issue by s888** [streadway/amqp#154]
I have changed rabbitmq's admin password to:  guest#

But when I use this password during connect it gives an error:
"strconv.ParseInt: parsing "guest": invalid syntax"

Code snippet:
str := "amqp://guest:guest#@localhost:5672/"
conn, err := amqp.Dial(str)

**Comment by mihaitodor** [comment]
Same for question marks in the password...

**Comment by michaelklishin** [comment]
Same root cause as #142.
