### ISSUE TITLE
Get count of messages awaiting acknowledgment

### ISSUE THREAD

**Issue by katcipis** [streadway/amqp#155]
Is there a way to do it ? It seems that I can only get the count of messages not awaiting acknowledgment:

https://godoc.org/github.com/streadway/amqp#Queue

This would be useful to do some automated testing to get bugs (when messages don't get acked for some reason)

**Comment by michaelklishin** [comment]
You can't do it using the protocol itself but this metric can be accessed via RabbitMQ HTTP API (used by the management plugin), for which [there is a Go client](https://github.com/michaelklishin/rabbit-hole).

**Comment by katcipis** [comment]
Thanks @michaelklishin.
