### ISSUE TITLE
No error when publishing without permission

### ISSUE THREAD

**Issue by rnapier** [streadway/amqp#156]
I called `Publish()` on an exchange that I didn't have permission to write to. I expected an error to be returned, but none was. Instead, my `NotifyReturn` and `Consume` channels were closed (so it appeared that I received an empty delivery and an empty return notice).

Checking the RabbitMQ logs, I found the root cause:

```
Channel error on connection <0.430.0> (127.0.0.1:49339 -> 127.0.0.1:5672, vhost: 'myvhost', user: 'myuser'), channel 1:
{amqp_error,access_refused,
            "access to exchange 'amq.default' in vhost 'myvhost' refused for user 'myuser'",
            'basic.publish'}
```

This was in response to:

```
    err = ch.Publish(
        "",         // exchange
        "register", // routing key
        true,       // mandatory
        false,      // immediate
        amqp.Publishing{
            ContentType: "application/x-www-form-urlencoded",
            ReplyTo:     clientQ.Name,
            Body:        []byte(connectString),
        })
```

where `err` was returned as `nil`.

**Comment by fsarron-nexway** [comment]
it seems that Channel.Publish() will always return nil, as internal Channel.sendOpen(), from which Channel.Publish() return the error.

**Comment by michaelklishin** [comment]
Error notifications in the protocol are entirely asynchronous. There is no response of any kind to `basic.publish`, even [Publisher Confirms](http://www.rabbitmq.com/confirms.html) are entirely asynchronous, by design.

**Comment by michaelklishin** [comment]
`basic.return` is orthogonal to permissions/authorization errors. Messages are returned when they cannot be routed.

**Comment by michaelklishin** [comment]
So, to handle errors like the above you need to register a channel error handler.
