### ISSUE TITLE
"slice bounds out of range" with frame_size = 0 configuration

### ISSUE THREAD

**Issue by trist4n** [streadway/amqp#161]
publishing to a server with frame_size=0 configured causes a runtime error, as the func (me *Channel) sendOpen function subtracts the frameHeaderSize (8) from what it believes the FrameSize is (in this case, 0). line 200, channel.go

this results in supposed slice indices of 0:-8, causing this error:

```
panic: runtime error: slice bounds out of range

github.com/streadway/amqp.(*Channel).sendOpen(0xc2080ca000, 0x7f9b66ece410, 0xc2080cc000, 0x0, 0x0)
        /home/vagrant/go/src/github.com/streadway/amqp/channel.go:225 +0x621
github.com/streadway/amqp.(*Channel).Publish(0xc2080ca000, 0x7fff628467b4, 0xd, 0x69c650, 0x8, 0xc200000000, 0xc2080c4360, 0x69c690, 0xa, 0x67f5f0, ...)
        /home/vagrant/go/src/github.com/streadway/amqp/channel.go:1318 +0x47d

this can be reproduced with a server containing the config '{frame_max, 0},' and the example code in _examples/simple-producer/producer.go, run with something like this:
go run producer.go -body=aaa -exchange="nope" -exchange-type="direct" -uri="amqp://nope:nope@nope.com/" -reliable=false
```

**Comment by trist4n** [comment]
pull request with a not so elegant fix submitted

**Comment by trist4n** [comment]
work around seems to be specifying a FrameSize in a DialConfig

amqp.DialConfig(uri, amqp.Config{
                Heartbeat:       10 * time.Second, // mirrors defaultHeartbeat that we cant access
                TLSClientConfig: tlsCfg,
                FrameSize:       131072, // default max size
});

**Comment by michaelklishin** [comment]
@trist4n is this still relevant? If so, you have pushed a test case above, would you be interested in submitting it as a pull request?

**Comment by trist4n** [comment]
I think the fix and test have already been merged?

https://github.com/streadway/amqp/commit/4247c9784c097d97496c545938d1c3392a996ad3

**Comment by michaelklishin** [comment]
Perfect, thanks for confirming!
