### ISSUE TITLE
Missing TLS timeout

### ISSUE THREAD

**Issue by joliver** [streadway/amqp#165]
During the TLS portion of the connection process, there is a missing timeout. Specifically, when the TLS [client is created and just before the handshake](https://github.com/streadway/amqp/blob/master/connection.go#L192), there needs to be a timeout set. Without this value there is an infinite timeout value which means the TLS handshake will stall.

The easy solution is to add a single statement:

https://golang.org/pkg/crypto/tls/#Conn.SetDeadline

`client.SetDeadline(config.TimeoutDuration) // or whatever configurable value you want`

Here's a stack trace to show you what's happening. We have observed this behavior when compiled against Go 1.4.2 and Go 1.5.2.  I have virtually identical stack traces from other machines.

```
goroutine 24 [IO wait, 125 minutes]:
net.(*pollDesc).Wait(0xc251acde90, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc251acde90, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc251acde30, 0xc24e6c3c00, 0x400, 0x400, 0x0, 0x7f6e3606ba48, 0xc23d3b6728)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc23621c050, 0xc24e6c3c00, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc24a0abb60, 0x7f6e182f04b8, 0xc23621c050, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc24857c000, 0x16, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).readHandshake(0xc24857c000, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:779 +0xe7
crypto/tls.(*Conn).clientHandshake(0xc24857c000, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/handshake_client.go:141 +0x110a
crypto/tls.(*Conn).Handshake(0xc24857c000, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:977 +0xf1
github.com/streadway/amqp.DialConfig(0xc23a48a980, 0x7e, 0xc23d04cec0, 0x1, 0x1, 0x81c0b0, 0x1, 0x0, 0x0, 0x37e11d600, ...)
    /tmp/buildd/src/github.com/streadway/amqp/connection.go:193 +0x59d
```

**Comment by michaelklishin** [comment]
I believe the problem here comes down to a race condition that possibly can be reproduced with a test but it's [quite difficult to do](https://github.com/streadway/amqp/pull/166#issuecomment-268774971) without

 * Connecting to a real RabbitMQ node running on a remote host
 * Having the same config as the reporter
 * Running the test 100s or 1000s times

So we applied #166 without a test.
