### ISSUE TITLE
Stops receiving messages after broker restart

### ISSUE THREAD

**Issue by ichilton** [streadway/amqp#169]
Hi,

I'm using some simple code like:
https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/go/receive_logs_topic.go

This seems to work ok under normal conditions, but if the broker gets restarted, the consumer doesn't seem to error or receive new messages - it silently sits there.

Is there any way of getting it to detect that the connection is no longer available and to raise an exception?

Thanks,

Ian

**Comment by michaelklishin** [comment]
Connection recovery is intentionally not a goal of this library. There are examples available in this repo and 3rd party packages that make it easier to integrate.
