### ISSUE TITLE
Get "unexpected command received" error when reusing a channel

### ISSUE THREAD

**Issue by RealHacker** [streadway/amqp#170]
In my application, each client uses the same connection and channel to send commands to rabbitmq: queue_declare, queue_bind, consume. Each client uses a temporary queue, so there is no conflict for exclusive queues.

My test script start many clients (each running in a separate goroutine) in a tight loop, and I get some "unexpected command received" errors, occuring inconsistently after sending different commands(declare/bind/consume). When I change my script to sleep for 100ms between starting each client, this problem goes away.

I read amqp code, and it seems this library sends a command and expects the next message returned on the channel to be the response to that command. In my test scenario with quick succession, this may not be the case, the response messages may arrive in different order from their commands, thus the library reports an error when everything is fine (no error logged on rabbitmq server side).

I am not sure if this is be design or a bug. Does this library expect users to not reuse a channel between different client sessions?

**Comment by michaelklishin** [comment]
```
I read amqp code, and it seems this library sends a command and expects the next message returned on the channel to be the response to that command.
```

which is how virtually all clients work in case of synchronous protocol operations.

What is in RabbitMQ log? How do you "reuse" a channel, is it used concurrently from multiple goroutines?

**Comment by RealHacker** [comment]
There is no error in RabbitMQ log.

This can be easily reproducible: just start several goroutines concurrently, each sending commands:declare/bind/consume, using the same channel. Since the execution of the goroutines are interleaved, the commands on the channel is like declare(goroutine1), declare(goroutine2), declare(goroutine3), bind(goroutine3)... however, the responses may not be of the same order, when amqp find an out-of-order response message, it reports an error.

if  the clients are running within the same thread/goroutine, nothing like this could happen, since the commands are all synchronous.

**Comment by michaelklishin** [comment]
@RealHacker not all libraries allow for concurrent use of channels. In fact, publishing is *not* supported by any of them that I'm aware of (this has been explained many times on RabbitMQ mailing list). So this can be by design.
