### ISSUE TITLE
Add support for client cert SASL authentication

### ISSUE THREAD

**Issue by ascotan** [streadway/amqp#171]
Right now the library can only handle password based PLAIN SASL auth. There is no support for EXTERNAL SASL support through rabbitmq_auth_mechanism_ssl.

This effectively means go (as a language) cannot be used in a rabbit deployment where client certs are managing the authentication to background components.

**Comment by michaelklishin** [comment]
This is addressed (and discussed) in https://github.com/streadway/amqp/pull/121, so marking as duplicate.
