### ISSUE TITLE
Can I use this in production ?

### ISSUE THREAD

**Issue by therahulprasad** [streadway/amqp#172]
Thanks for the awesome library. I saw "build failing" and "Beta" tag, which got me confused.
Should I use amqp in production ? Or is there any stable branch which I can use in production environment ?

**Comment by pnordahl** [comment]
As far as I can tell, it's not being actively maintained. Streadway may swing back and fix the build errors, but in the interim my personal advice is to clone and revert to revision 56eb08f. You can look at the build history here: https://travis-ci.org/streadway/amqp/builds and make your own determination as to what is the most stable revision to use.

**Comment by michaelklishin** [comment]
It's been used in production for several years. See #215 if recent activity concerns you. So yes, you probably can :)
