### ISSUE TITLE
Severe channel memory leak

### ISSUE THREAD

**Issue by shadyxu** [streadway/amqp#174]
I fetch data from some RabbitMQ server and send data to another RabbitMQ server after some operations. The memory used continues to increase. Below is the result of pprof:

Showing top 10 nodes out of 17 (cum >= 58.52MB)
      flat  flat%   sum%        cum   cum%
 1478.50MB 83.65% 83.65%  1667.06MB 94.32%  github.com/streadway/amqp.(*Channel).recvContent
  188.56MB 10.67% 94.32%   188.56MB 10.67%  github.com/streadway/amqp.newDelivery
      52MB  2.94% 97.26%       52MB  2.94%  github.com/streadway/amqp.readShortstr
   28.79MB  1.63% 98.89%    28.79MB  1.63%  regexp.(*bitState).reset
         0     0% 98.89%   188.56MB 10.67%  github.com/streadway/amqp.(*Channel).dispatch
         0     0% 98.89%  1667.06MB 94.32%  github.com/streadway/amqp.(*Connection).demux
         0     0% 98.89%  1667.06MB 94.32%  github.com/streadway/amqp.(*Connection).dispatchN
         0     0% 98.89%  1725.58MB 97.63%  github.com/streadway/amqp.(*Connection).reader
         0     0% 98.89%    44.50MB  2.52%  github.com/streadway/amqp.(*basicDeliver).read
         0     0% 98.89%    58.52MB  3.31%  github.com/streadway/amqp.(*reader).ReadFrame

**Comment by michaelklishin** [comment]
@shadyxu that does not suggest a memory leak. Does the number of channels continuously increase? It can be an application issue.

Do you use manual acknowledgement mode? If not, RabbitMQ will deliver messages as far as possible, and your consumer may or may not keep up (but deliveries will be kept in memory).

`recvContent` certainly can hint at the latter.

**Comment by shadyxu** [comment]
@michaelklishin Yes the problem is caused by too much data from RabbitMQ, though using manual acknowledgement does not solve the problem because data will be blocked at the MQ side. Thanks for the hint.

**Comment by michaelklishin** [comment]
@shadyxu what do you mean "blocked at the MQ side"? If your consumer cannot keep up with publishers, it's up to you to resolve it, e.g. by setting max queue limit or message TTL.

This is not a problem with the library. TCP backpressure for such cases is possible, e.g. Java client in 3.5.x has it, but it by no means replaces manual acknowledgements.

**Comment by shadyxu** [comment]
@michaelklishin Sorry for the misunderstanding. By "blocked at the MQ side" I mean the consumer cannot keep up with the publishers. I've solved the problem and it's indeed not a problem with this library.
