### ISSUE TITLE
transport maybe block caused by socket accumulate the readbuffer

### ISSUE THREAD

**Issue by liutaihua** [streadway/amqp#176]
I use amqp lib as following way:
create some connection at first, and random use one of them to open channel for publish or consume.
Issue， with application server uptime increament, one day or hours,  i found the os tell me Recv-Q of connection heap up a lot of data(netstat -nat|grep 5672), 

I don't understand, why socket read buffer heap up a lot of data. and i take a look at the source code, there have a goroutine for read all data, and handle theme in next logic.  maybe the follow-up func call blocked? so the next read loop does not run?

because above reason, may cause the remote(amqp server) of this problem connection can not send data through socket, because local of this connection's Recv-Q has full,   thereby block the new open channel or publish. 

use same connection with multi goroutine
should i change my way of connection use?

**Comment by michaelklishin** [comment]
@liutaihua TCP read buffer can be full because your consumer does not keep up with the rate of deliveries it is getting.

**Comment by michaelklishin** [comment]
Assuming this was answered.
