### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by awissu** [streadway/amqp#179]
Hi!
The following program crashes on x86 architecture:

[  155s] --- FAIL: TestGoFuzzCrashers (0.00s)
[  155s] panic: runtime error: makeslice: len out of range [recovered]
[  155s]    panic: runtime error: makeslice: len out of range

Steps to reproduce:
- Create spec: https://build.opensuse.org/package/view_file/home:awissu:branches:devel:languages:go/golang-github-streadway-amqp/golang-github-streadway-amqp.spec?expand=1
- Build: https://build.opensuse.org/build/home:awissu:branches:devel:languages:go/openSUSE_Factory/i586/golang-github-streadway-amqp/_log

**Comment by michaelklishin** [comment]
We haven't see this error recently and the URLs 404.
