### ISSUE TITLE
remote error: handshake failure Mutual TLS to RabbitMQ Server

### ISSUE THREAD

**Issue by RogerTavares1** [streadway/amqp#184]
So I am having a problem authenticating my client certs on my RabbitMQ Server using Go-lang. I can however do so with a python script and the same client certs. I have provided the code I am using below and would like to know if I am doing something wrong any help would be appreciated.
```
func main() {
    cfg := new(tls.Config) 
  
    cfg.MinVersion = tls.VersionTLS12
    cfg.MaxVersion = tls.VersionTLS12
  
    cfg.CipherSuites = []uint16{
    tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 }  
    
    cfg.RootCAs = x509.NewCertPool()
    
    if ca, err := ioutil.ReadFile("certs/cacert.pem"); err == nil {
      cfg.RootCAs.AppendCertsFromPEM(ca)
    }
    
    cfg.ServerName = "dev"
    cfg.PreferServerCipherSuites = true
    
    if cert, err := tls.LoadX509KeyPair("certs/cert.pem", "certs/key.pem"); err == nil {
      cfg.Certificates = append(cfg.Certificates, cert)
    }
    
    connection, connectionError := amqp.DialTLS("amqps://dev:5671/", cfg)
    if connectionError != nil {
      log.Printf("%v", connectionError)
    } else
    {
       // Create channel, queue etc.
    }
}
```

**Comment by RogerTavares1** [comment]
I was able to successfully establish a Mutual SSL connection to the RabbitMQ Server. The process I took was to create the secure TCP connection using the OpenSSL library and then tunnelling a amqp connection through that. The code I used to do this is bellow:

```
ctx, error := openssl.NewCtxFromFiles("cert.pem", "key.pem")
  if error != nil {
    log.Fatal(error)
  }
  
  error = ctx.LoadVerifyLocations("certs/cacert.pem", "")
  
  if error != nil {
    log.Fatal(error)
  }
  
  sslConnection, error := openssl.Dial("tcp", "dev:5671", ctx, 0) 
  
  if error != nil {
    log.Fatal(error)
  }else
  {
    config :=  amqp.Config{
      Vhost:     "/",
      SASL:      []amqp.Authentication{&amqp.PlainAuth{"guest", "guest"}},
    }
    
    amqpConnection, amqpConnectionError := amqp.Open(sslConnection, config)
  }
```
Hope this is useful to anyone else who comes across the same or similar problem when mutual SSL is required.

**Comment by LathaSrinivasan** [comment]
Hi Roger,
I am running into the same issue with RabbitMQ 3.6.9 and Erlang/OTP 19. Basically I am able to successfully connect to the rabbitMQ server using the openssl commands listed in  the troubleshooting guide( https://www.rabbitmq.com/troubleshooting-ssl.html), but when I try to programmatically connect it from a go service, I get an "unknown CA" error. Which openssl library did you use? I tried to issue a go get on https://github.com/spacemonkeygo/openssl but got errors. Thanks!
