### ISSUE TITLE
Unable to connect to amqp:// via DialTLS

### ISSUE THREAD

**Issue by cbandy** [streadway/amqp#190]
The [documentation for `DialTLS`](https://godoc.org/github.com/streadway/amqp#DialTLS) says:

> DialTLS uses the provided tls.Config when encountering an amqps:// scheme.

This sounds great for us, since we prefer SSL/TLS in production but typically develop without it. I expected I could pass some reasonable `tls.Config` regardless of the connection string:

``` go
package main

import (
    "crypto/tls"
    "testing"

    "github.com/streadway/amqp"
)

func TestDialTLSWithAMQP(t *testing.T) {
    uri := "amqp://user:pass@rabbitmq-1.lxc/test"

    conn, err := amqp.DialTLS(uri, &tls.Config{MinVersion: tls.VersionTLS12})
    if err != nil {
        t.Fatalf("Expected no error, got %v", err)
    }
    defer conn.Close()
}
```

However, using `DialTLS` this way results in an error:

```
=== RUN TestDialTLSWithAMQP
--- FAIL: TestDialTLSWithAMQP (0.16s)
        cxn_test.go:15: Expected no error, got tls: oversized record received with length 20480
FAIL
exit status 1
FAIL    test    0.164s
```

Changing the connection string to `amqps://user:pass@rabbitmq-1.lxc/test` works perfectly.

Am I doing something wrong? Is the documentation incorrect in this case?

For now we do the following:

``` go
var conn *amqp.Connection
var err error

if strings.HasPrefix(uri, "amqps") {
    conn, err = amqp.DialTLS(uri, &tls.Config{MinVersion: tls.VersionTLS12})
} else {
    conn, err = amqp.Dial(uri)
}
```

**Comment by michaelklishin** [comment]
Given the commit above that corrects a URI in rabbitmq-tutorials, is this still relevant?

**Comment by cbandy** [comment]
Yes. I can see that I wasn't clear. I'll check again why I said "works perfectly."

The [documentation says](https://github.com/streadway/amqp/blob/1b8853833a94be8ba57fd121a8651f7221e5b051/doc.go#L101-L103):

> DialTLS will use the provided tls.Config when it encounters an amqps:// scheme and will dial a plain connection when it encounters an amqp:// scheme.

My interpretation is that DialTLS will connect without TLS for an `amqp://` URI. Is that how DialTLS is supposed to work?

**Comment by michaelklishin** [comment]
@cbandy yes, my reading of the docs is the same. Well, that's a curious design choice (compared to all other clients I am aware of, at least).

**Comment by cbandy** [comment]
The relationship between the Dial functions, `Config`, and URIs is complex.
