### ISSUE TITLE
Is there a way to query the server application name / version?

### ISSUE THREAD

**Issue by liquidmetal** [streadway/amqp#195]
I have some dependencies on `rabbitmq3.6.1+`. This means I can't use older versions of rabbitmq. Is there a way I can query if I'm using the correct version of rabbitmq?

I tried `connection.Major` and `connection.Minor` - but those only give me the AMQP version. Is there a way to figure out the server name/version? I'm not sure if this is even possible - so thought I'd post here.

**Comment by michaelklishin** [comment]
Connection context has vendor information but that is a free form string. You probably want to use https://github.com/michaelklishin/rabbit-hole and specifically the overview and node list endpoints.

Please post questions to rabbitmq-users.

**Comment by liquidmetal** [comment]
Thanks!
