### ISSUE TITLE
Infinite message confirmation with DeliveryTag=0

### ISSUE THREAD

**Issue by steven-zou** [streadway/amqp#199]
Here is the code I used. 

------------------------------------------------------------------
` if err := pub.Confirm(false); err != nil {
			utils.GetLogger().Warning("Publisher confirms not supported:%s", err)
			close(confirm) // Confirms not supported, simulate by always nacking
		} else {
			pub.NotifyPublish(confirm)
		}

for{
select {
			case confirmed := <-confirm:
				if !confirmed.Ack {
					if confirmed.DeliveryTag > 0 {
						utils.GetLogger().Warning("nack message %d, body: %q", confirmed.DeliveryTag, string(body.ToRawMessage()))
					}
				}
 ......
}//end select
}//end for `

---------------------------------------------------

If the connection is broken, for example, network is down, there will be infinite confirmation in the confirm channel with deliveryTag is 0. Why these confirmation are coming? Is work as designed? I'm NOT sure. So I raised this issue for discussion and ways to resolve this issue.

**Comment by michaelklishin** [comment]
Publisher confirms cannot be coming if the network is down but there could be (a limited, and probably short) number of not-yet-processed `basic.ack` frames buffered in a client.

**Comment by steven-zou** [comment]
Right, I think the problem may not come from amqp client lib. I'll check other parts to identify the root cause. And about this issue, I'll close it!
