### ISSUE TITLE
Using Channels/connections from multiple goroutines

### ISSUE THREAD

**Issue by michael-stevens** [streadway/amqp#208]
Hi,

I'd like to use channels and connections from multiple goroutines, in the same way as db connections can be used concurrently. Looking at the docs, I'm unable to tell if this is safe - on the one hand, there's no explicit mention of thread safety, on the other hand, there are a number of reference to the desirability of long lived connections, mentions of locking, etc which makes me think it might be ok. What are the rules?

**Comment by michaelklishin** [comment]
Channels are not supposed to be shared for concurrent publishing (in this client and in general).

**Comment by tonykung06** [comment]
it is thread safe: see `https://github.com/streadway/amqp/blob/master/channel.go#L1285`

**Comment by sodaling** [comment]
> Channels are not supposed to be shared for concurrent publishing (in this client and in general).

So is it thread safe? I see that the mutex on the connection is called when the send method is called?
At the same time, if it is not safe to share a channel under different groutines, should we create a new channel for each groutine?
The last thing I want to ask is that amqp's channel is mainly for multi-threaded concurrency. Is it appropriate to call the mutex on the connection when the send method is called?
