### ISSUE TITLE
autoreconnect after losing internet and gain internet connection again

### ISSUE THREAD

**Issue by duyhtq** [streadway/amqp#211]
it looks like rabbitmq amqp doesn't autoreconnect after losing internet and gaining internet connection again.  the only option is to stop the client code and restart it.  is there anyway to do "autoreconnect"?  thanks.

**Comment by orlando** [comment]
@duyhtq reconnection is one of the non-goals of this project, https://github.com/streadway/amqp#non-goals. So I think this is never going to be implemented.

**Comment by michaelklishin** [comment]
We have another library in mind that would cover this but as @orlando points out above, it's one of the specific non-goals for this project, even though automatic recovery is a fairly common feature for RabbitMQ client libraries today.
