### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by orlando** [streadway/amqp#215]
Hey @streadway, looks like you are not actively maintaining this project. We are using this project at the moment, and some of the pull request fixes some issues we are having in our setup.

I think this is the most used rabbitmq library for go at the moment (correct me if I'm wrong here), are you looking for maintainers?, happy to help

Thanks!

**Comment by michaelklishin** [comment]
@streadway a couple of RabbitMQ team members would be interested in helping push this library forward, too.

**Comment by streadway** [comment]
Hey. Indeed I struggle to make the time to review and maintain the project. I'm happy to accept help maintaining the project. How would you suggest continuing?

**Comment by orlando** [comment]
@streadway I was looking just to help to triage and verify the current PRs, as well as checking current and future issues. We are using actively RabbitMQ and this library at the moment, so it's a good time for us to contribute to this project.

Also, I'm ok continue working on this repo.

@michaelklishin What do you guys have in mind for this?

**Comment by michaelklishin** [comment]
@streadway I think granting a few people project access and giving them some reasonable amount of freedom to accept pull requests can make a lot of difference.

@orlando mostly fixing known issues, cleaning up the list of pull requests, and then seeing what features may be missing. RabbitMQ clients don't change that often so I don't think there are any major changes we have in mind.

**Comment by michaelklishin** [comment]
Hit "Comment" too early. Our team's goal is to make this a rock solid client we can confidently recommend and use in our tutorials, that's mostly it :)

**Comment by gaffneyc** [comment]
It would be great to see some of the outstanding issues and pull requests tackled. There are a few dealing with some tricky race conditions that have been outstanding for a while (partly because of the difficulty writing tests for them).

Would love to help out in some capacity as well.

**Comment by michaelklishin** [comment]
@streadway what can folks such as @gaffneyc and I do to get commit permissions and help move this project forward?

**Comment by michaelklishin** [comment]
I'd really hate to do this (and don't mean it to sound like a threat) but if @streadway and the community cannot work out a meaningful way to get more people involved in maintaining this project, the only solution I see is a community-driven fork that multiple interested developers get behind.

**Comment by streadway** [comment]
I'm all for supporting a better maintenance model and granting wider access with a plan for the longer term. I'm working through the scenario of opening up the repository with the legal department at SoundCloud. It's been taking a little to get the right people together. Sorry about that.

@michaelklishin, is the RabbitMQ team willing to act as primary maintainers?

**Comment by michaelklishin** [comment]
@streadway we are. I completely understand that it can take a while to get legal's permission, sorry if I sounded like an alarmist. Thank you for the update :)

**Comment by michaelklishin** [comment]
I'm going to post an update on behalf of @streadway and @gerhard :) We had a Hangout earlier today and discussed our short and medium term plans for this library. Long story short, we want to clean up the issues and pull requests first, improving test coverage along the way. No major changes to this client are planned. Opinionated features such as automatic connection recovery will live in a separate library. We plan to support two most recent Go versions ("up to N-1").

Expect some activity next week. Oh, and of course we'd definitely consider community contributions. It's not a takeover plan from team RabbitMQ and there is no company-specific agenda ;)

**Comment by orlando** [comment]
Awesome 🎉 , let me know If I can help in anyway @michaelklishin @streadway @gerhard.

**Comment by michaelklishin** [comment]
@orlando you can go through the issues and take a look at which ones are duplicates, questions, need more information/way to reproduce, and which ones look legit and clear enough. That's would be huge help.

Doing the same with open pull requests and evaluating them would help enormously as well. Of course, submitting fixes for legit issues is always welcome. Just try to make sure we are improving our automated test coverage where possible/worth the effort.

**Comment by orlando** [comment]
Sounds good @michaelklishin, thanks for the effort guys. 

I'll close this issue.

**Comment by streadway** [comment]
Thanks @michaelklishin and @gerhard for helping the community and this library! I am quiet happy for the support.
