### ISSUE TITLE
Worker hang with Unacked message

### ISSUE THREAD

**Issue by huyphams** [streadway/amqp#217]
I'm using amqp with this code:

Make chanel code
```
func (r *Helper) MakeChanel(name string) (*amqp.Channel, error) {
	ch, err := r.Rabbit.Channel()
	if err != nil {
		fmt.Println("[ERROR] Failed open chanel", err)
		return nil, err
	}
	_, err = ch.QueueDeclare(
		name,  // name
		false, // durable
		false, // delete when unused
		false, // exclusive
		false, // no-wait
		nil,   // arguments
	)
	if err != nil {
		return ch, err
	}

      // This config to make sure rabbit delivery only one message to worker and waiting worker done to delivery next message.
	err = ch.Qos(1, 0, false)
	return ch, err
}
```

Then I make a comsumer

```

func (r *Helper) MakeConsumeWithTag(name string, tag string, ch *amqp.Channel, handler HandlerFunc) {
	msgs, err := ch.Consume(
		name,  // queue
		tag,   // consumer
		false, // auto-ack
		false, // exclusive
		false, // no-local
		false, // no-wait
		nil,   // args
	)

	if err != nil {
		fmt.Println("[ERROR] Make consume with tag failed", err)
		panic(err)
	}
	go func() {
		for d := range msgs {
			handler(&d)
			err := d.Ack(false)
			if err != nil {
				d.Ack(false)
			}
		}
	}()
}
```
```
MakeConsumeWithTag(JobQueueName, strconv.Itoa(i), c.JobChanel, service.JobHandler)
```
JobHandler is simple function without infinite loops, just get message and store them to database.

I have an error (rarely: 0-1 time in a month). when rabbit stop delivery message and I noticed that all worker stay at `Unacked` in rabbit dashboard.

**Comment by michaelklishin** [comment]
Please see [RabbitMQ documentation on acknowledgements](http://www.rabbitmq.com/confirms.html). Your code seems to be attempting double acknowledgements: I suspect this is a result of a misunderstanding.

**Comment by justinfx** [comment]
I'm currently trying to track down similar sounding behaviour in more than one of my own services making use of this library. @michaelklishin, can you explain where the double-ack is happening in the original example? I am seeing auto-ack being disabled, and a manual ack being done in the handler.

**Comment by huyphams** [comment]
@michaelklishin sorry my typo mistake but I'm sure no double ack in my production mode (just fixed the code above).
FYR: I haven't maintained the project for a year so I didn't it fixed or not.
Thank you.

**Comment by michaelklishin** [comment]
@justinfx in the OP's snippet there is only one acknowledgement. My response is actually wrong, as any double acknowledgement scenario would result in a channel exception, which means all outstanding deliveries will be requeued.

However, unacknowledged deliveries is pretty much always an application-specific problem. For clients that do not support protocol method tracing (e.g. Bunny does at debug log level), [Wireshark](https://www.rabbitmq.com/amqp-wireshark.html) is a really efficient way of gathering more information about what the app receives and sends.
