### ISSUE TITLE
Multiple calls to Connection.Close() results in error

### ISSUE THREAD

**Issue by DmitriyMV** [streadway/amqp#218]
Basically this:
```
	Error:		Received unexpected error:
			write tcp 10.100.253.18:51848->192.168.0.222:5672: use of closed network connection
```
When trying to close several times.

**Comment by michaelklishin** [comment]
And what do you expect to happen? Closing a connection multiple times is an error: this is not something the protocol or TCP sockets allow you to do.

**Comment by michaelklishin** [comment]
I'm closing this because there's no information on what you expected to have happened and the current error message is not that cryptic.

See #219 for what I believe all client libraries should do.

**Comment by DmitriyMV** [comment]
I believe multiple calls to Close should result in last error or no-op if connection is already closed. There is already sync.Once inside - just wrap the logic.
