### ISSUE TITLE
virtualhost is not handled corretly if no / as prefix.

### ISSUE THREAD

**Issue by systembugtj** [streadway/amqp#220]
Below uri can be used correctly to publish
amqp://username:password@host:5672/
amqp://username:password@host:5672//test

But if virtualhost is "test" not "/test", it won't be able to publish
amqp://username:password@host:5672/test

Repro Rabbitmq 3.6.5

**Comment by michaelklishin** [comment]
@systembugtj can you please be more specific about what your code looks like and what exactly "won't be able to publish" means? Thanks.

**Comment by michaelklishin** [comment]
Closing as there was no response. I suspect the root cause is the same as in #142.

**Comment by wilbeibi** [comment]
Meet same issue. Rabbitmq management UI do accepts non percent-encoding characters.
