### ISSUE TITLE
Running go test with -race flag takes a lot of cpu time and memory.

### ISSUE THREAD

**Issue by DmitriyMV** [streadway/amqp#229]
On mine Linux desktop - it eats more than 8gb of memory (essentially disabling my machine). The culprit is `TestGoFuzzCrashers`.

**Comment by michaelklishin** [comment]
See https://github.com/streadway/amqp/pull/197 for an explanation. Unfortunately merging the proposed changes break CI in ways that I cannot reproduce anywhere else.
