### ISSUE TITLE
Make sure that AMQP 0-9-1 handshake has a timeout

### ISSUE THREAD

**Issue by michaelklishin** [streadway/amqp#232]
This was originally discussed in https://github.com/streadway/amqp/pull/166. We need to make sure that there is a timeout for the handshake operation (à la what Go's HTTP transport does using a one-off timer) and that it uses the same default as connection (dial) timeout for TCP and TLS connections.

**Comment by streadway** [comment]
https://github.com/streadway/amqp/tree/timeout
