### ISSUE TITLE
All chan Delivery will close when a queue is deleted

### ISSUE THREAD

**Issue by liukai2012** [streadway/amqp#235]
Now I create 5 channels on a connection  and all channels and the connection will be closed when I delete a queue on the web。I think it is wrong。If a queue is deleted，the channel that monitor the queue is closed，but others should be open and continue to service。Who can help me？ @michaelklishin

**Comment by michaelklishin** [comment]
Deleting a queue will cancel its consumer (and notify them) but not affect channels. Your channels are almost certainly closed due to a channel-level exception. What exactly it is, I cannot know: see the log.

**Comment by liukai2012** [comment]
When I delete a queue on the web， The Chan recieves a amqp.Error  by NotifyClose，The Code is 503. Consumers are cancelled on the same connection. I don't know why, but it will appear every
 time.  Can you try it and Thank you@michaelklishin

**Comment by michaelklishin** [comment]
@liukai2012 [all consumers on that queue are expected to be cancelled](https://www.rabbitmq.com/consumer-cancel.html), regardless of their connection or channel.
See server logs for clues.

I cannot help you without seeing your code and logs.

**Comment by liukai2012** [comment]
I catch some packages by wireshark.  When I connect rabbitmq by golang sdk and delete a queue, I receive two frames, one is basic cancel and other is connection. close.   When I use java sdk, I only receive  basic cancel frame. 

The frame is : 
![image](https://cloud.githubusercontent.com/assets/17694292/21640911/417d4704-d2b3-11e6-9141-7aa5880807b1.png)

I don't know why rabbitmq has different actions between golang and java. Help me please! @michaelklishin

**Comment by liukai2012** [comment]
The connection code is Simple and I don't show it.
Here is my consumer code:

`func (rabbitmq *Rabbitmq) ConsumerMsg(queue string, ch *amqp.Channel) error {
	defer ch.Close()

	q, err := ch.QueueDeclare(
		queue, // name
		true,  // durable
		false, // delete when usused
		false, // exclusive
		false, // no-wait
		nil,   // arguments
	)

	if err != nil {
		utils.FailOnError(err, "Failed to declare a queue")
		return err
	}

	msgs, err := ch.Consume(
		q.Name, // queue
		"",     // consumer
		false,  // auto-ack
		false,  // exclusive
		false,  // no-local
		false,  // no-wait
		nil,    // args
	)

	if err != nil {
		utils.FailOnError(err, "Failed to declare a queue")
		return err
	}
	l4g.Debug("Start to consumer, queue = %s", queue)
	for msg := range msgs {
		mlist, err := cache.MsgCaches.Get(queue)
		if err != nil {
			break
		}
		len := mlist.Set(msg)
		if len > rabbitmq.MaxMsgPerQueue {
			time.Sleep(model.SLEEPTIME * time.Second)
		}
	}

	l4g.Debug("End to consumer, queue = %s", queue)

	return nil
}`

**Comment by michaelklishin** [comment]
`connection.close` means your code did something that's considered to be a protocol-level exception. It should be very visible in server logs.

**Comment by liukai2012** [comment]
I don't think so. I find the reason.   In golang sdk, receive the basic.cancel frame, it will ack. The Code is:

`case *basicCancel:
		for _, c := range me.cancels {
			c <- m.ConsumerTag
		}
		me.send(me, &basicCancelOk{ConsumerTag: m.ConsumerTag})`

When rabbitmq receive the cancel ok, it will send connection.close. So I will catch four frame by wireshark.

In java sdk, it receive basic.cancel and it does nothing and rabbitmq will not send connection.close. So I catch one frame by wireshark.

**Comment by liukai2012** [comment]
Now I change the code in golang sdk. I remove  the `me.send(me, &basicCancelOk{ConsumerTag: m.ConsumerTag})`. 

When I delete a queue, it will affect the Delivery and the connection is ok. @michaelklishin

**Comment by liukai2012** [comment]
Do you think it's better that delelte `me.send(me, &basicCancelOk{ConsumerTag: m.ConsumerTag})` just like java sdk.
