### ISSUE TITLE
Changing Qos prefetch-count at runtime

### ISSUE THREAD

**Issue by ganglio** [streadway/amqp#236]
Hello there,

I'm using the prefetch-count to manage the workers pool size in my app and I would like to change it at runtime (meaning after the channel.Consume has been invoked.

When I try, tho, it just gets ignored.

Is there any way I can adjust the prefetch_count while the consumer channel is already running?

Thanks and ciao,
Roberto

**Comment by michaelklishin** [comment]
@ganglio see [RabbitMQ docs](http://www.rabbitmq.com/consumer-prefetch.html).
