### ISSUE TITLE
rabbimq uri can not contains symbol (?)

### ISSUE THREAD

**Issue by davidstack** [streadway/amqp#243]
if my mq uri is:`amqp://docker:123456a?@10.110.20.179:5672/` ,it will failed when connect to mq with this log:
AMQP scheme must be either 'amqp://' or 'amqps://'

when i check the code,i find the bug:
`func ParseURI(uri string) (URI, error) {
	builder := defaultURI

	u, err := url.Parse(uri)
	if err != nil {
		return builder, err
	}

	defaultPort, okScheme := schemePorts[u.Scheme]

	if okScheme {
		builder.Scheme = u.Scheme
	} else {
		return builder, errURIScheme
	}`
this function use net.url to parase the amq uri. we know that in the url,? is used to set parament.

**Comment by gerhard** [comment]
Addressed in #244
