### ISSUE TITLE
inequivalent arg where both args appear to be the exact same

### ISSUE THREAD

**Issue by Southclaws** [streadway/amqp#247]
Just got this very confusing error message:

`Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'tasksready.0099.j-12345678-1234-1234-1234-000000000001' in vhost '/': received '259200000' but current is '259200000'"`

and I thought "259200000 != 259200000 ???"

I later found this was the difference between me doing:

`"x-expires": int32(259200000),`, `"x-expires": 259200000,` and `"x-expires": "259200000",`

still, I think the error reporting could be explicit about types if there's a type mismatch!

**Comment by michaelklishin** [comment]
The error comes from RabbitMQ, not this client. Yes, expiration is a string in the AMQP 0-9-1 spec :/ That's an unfortunate fact that has been documented for many years. There is nothing specific to this client.
