### ISSUE TITLE
AMQP Dial Error

### ISSUE THREAD

**Issue by Ch3ck** [streadway/amqp#257]
I get this error while trying to connect to RabbitMQ
`tls: oversized record received with length 20480`

How I got the error:
`conn, err := amqp.Dial("c.Server")
if err != nil {
    log.Printf("Error connecting to Rabbit MQ: %+v", err)
}`
I can't seem to find a way around this.

**Comment by jtorvald** [comment]
I had the same error when I wrote to a queue or exchange with different configuration than the one that already existed (if I remember correctly). If you're still in development: try to remove them and set them up correctly and make sure in all your calls to declare them the same

**Comment by Ch3ck** [comment]
@jtorvald I guess the way around this is looking at the server config settings?

**Comment by michaelklishin** [comment]
@jtorvald I think you are confusing with with a channel exception `precondition_failed`. This has nothing to do with this issue which reveals a message from the Erlang TLS app.

@Ch3ck this belongs to rabbitmq-users, not here, but anyhow: see and post server logs. RabbitMQ does not implement TLS, Erlang/OTP does, so first two things I'd do are

 * Make sure that your client is actually instructed to use TLS (`amqp.Dial("c.Server")` does not use TLS but this may or may not be your entire code)
 * Upgrade to at least Erlang 19.2, ideally 19.3.

**Comment by michaelklishin** [comment]
In case it's not clear: both server and client must be instructed to use TLS. If either of them isn't you will get weird errors, timeouts, etc. This is true for any client library.

**Comment by Ch3ck** [comment]
Thanks, @michaelklishin the issue was coming from my server end. I fixed it :+1:
