### ISSUE TITLE
Is there any plans for support URI query parameters in DSN?

### ISSUE THREAD

**Issue by grafov** [streadway/amqp#262]
As described in https://www.rabbitmq.com/uri-query-parameters.html only Erlang client has ability to parse additional parameters in DSN. Quick look into code of golang client confirms that it really parses only base DSN (described in https://www.rabbitmq.com/uri-spec.html). Is there any plans for support additional URI parameters in golang client?

**Comment by michaelklishin** [comment]
If someone contributes it, we would consider it.
