### ISSUE TITLE
Questions about Publisher confirms

### ISSUE THREAD

**Issue by orange4glace** [streadway/amqp#282]
1. About this client
The doc describes about Publish function like this

> This can return an error when the channel, connection or socket is closed.  **The
> error or lack of an error does not indicate whether the server has received this
> publishing.**
> **It is possible for publishing to not reach the broker if the underlying socket
> is shut down without pending publishing packets being flushed from the kernel
> buffers.**  The easy way of making it probable that all publishings reach the
> server is to always call Connection.Close before terminating your publishing
> application.  The way to ensure that all publishings reach the server is to add
> a listener to Channel.NotifyPublish and put the channel in confirm mode with
> Channel.Confirm.  Publishing delivery tags and their corresponding
> confirmations start at 1.  Exit when all publishings are confirmed.

When the situation(text which bold style) happens, although Publish() will not return any error but the packet will be lost and it will not arrive to the server. At the end, server will not send any ack/nack response. So to ensure the delivery, I have to wait for seconds for the confirm channel and when not receiving any response, re-publish the message with Publish() again.
This is what I've understood but every examples acts ack/nack packet is guaranteed after call Publish() (if there's no returning error)
Why is that? Does ack/nack response packet is guaranteed to be arrived when there's no returning error in Publish() ?

2. Design of Delivery tag

Since delivery tag is channel scoped, I know it's true the producer can't know the delivery tag immediately after publishing.
For one-by-one publishing, we can publish the next one after ack the previous one
```
while {
	// get next message
	msg = get_next_message()
	// publish the msg to the server
	channel.publish(msg)
	// block until getting the confirm
	result = channel.notice_confirm()
}
```
we can sure the `result` is the confirmation with the latest sent message regardless of the `result.DeliveryTag` if there is no other publishers with same channel within the process even there're multiple publishers over entire connected clients. So, it's good.

But if we publish multiple messages at once, Is there no way to recognize which confirmation is for which message? (with situations one with multiple publishers and one with single publisher itself)

And one more, how is different with one-by-one publisher confirm and transaction although both send messages one-by-one?

Thanks

**Comment by michaelklishin** [comment]
1. See [heartbeats](http://rabbitmq.com/heartbeats.html). There are confirms tests that demonstrate how timeout can be used but since acknowledgements are delivered using a Go channel, it should be no different from consuming from a channel with a timeout elsewhere.
2. See #279.

**Comment by orange4glace** [comment]
@michaelklishin 
1. Got it. i was an idiot.

2. What I want to know is can I know which message is sent and which is not when sending multiple messages.
```
private volatile SortedSet<Long> unconfirmedSet =
    Collections.synchronizedSortedSet(new TreeSet());

...

ch.setConfirmListener(new ConfirmListener() {
    public void handleAck(long seqNo, boolean multiple) {
        if (multiple) {
            unconfirmedSet.headSet(seqNo+1).clear();
        } else {
            unconfirmedSet.remove(seqNo);
        }
    }
    public void handleNack(long seqNo, boolean multiple) {
        // handle the lost messages somehow
    }
});
ch.confirmSelect();
for (long i = 0; i < MSG_COUNT; ++i) {
     unconfirmedSet.add(ch.getNextPublishSeqNo());
     ch.basicPublish("", QUEUE_NAME, MessageProperties.PERSISTENT_BASIC,
                       "nop".getBytes());
 }
while (unconfirmedSet.size() > 0)
     Thread.sleep(10);
```
When multiple messages are sent, we don't know a delivery tag of each messages.
But I know whether every messages are sent by checking the size of the arrived confirmations (like code above)
Since the publisher confirms order is not guaranteed, (https://www.rabbitmq.com/confirms.html, #Ordering Considerations for Publisher Confirms)
when failed to acks one or more of them, should I re-publish all of them although some of them are acked? (which is inefficient)

and while not batching, Is one-by-one publishing (publish -> wait for ack -> publish next, synchronously) the only way to guarantee the publish?

Thank you.

**Comment by michaelklishin** [comment]
@orange4glace I believe this is exactly the same question as #279.

**Comment by orange4glace** [comment]
@michaelklishin 
What a dumb. I had thought it was exchange or queue scope instead of channel even I mentioned about it =_= ;

Thanks!

**Comment by michaelklishin** [comment]
@orange4glace no worries :)
