### ISSUE TITLE
DialTLS side effects the *tls.Config

### ISSUE THREAD

**Issue by kevinjos** [streadway/amqp#284]
My objective is to attempt to Dial a list of hosts belonging to the same cluster and return the first successful connection.

Assuming that a slice of *amqp.URIs is used where dialing the first URI in the slice is expected to fail and the second URI is expected to succeed. For Example 1 below both DialTLS calls fail. Example 2 succeeds on the second DialTLS call. Is this expected behavior? Is Example 2 the correct implementation? Does DialTLS modify the *tls.Config on failure in a way that guarantees subsequent uses of the same tls.Config will also fail?

Example 1:
```
func DialTLS(uricfgs []*amqp.URI, tlscfg *tls.Config) (conn *amqp.Connection, err error) {
	for _, uricfg := range uricfgs {
		conn, err = amqp.DialTLS(uriConfig.String(), newtlscfg)
		if err == nil {
			break
		}
	}
	return conn, err
}
```

Example 2:
```
func DialTLS(uricfgs []*amqp.URI, tlscfg *tls.Config) (conn *amqp.Connection, err error) {
	newtlscfg := new(tls.Config)
	for _, uricfg := range uricfgs {
		*newtlscfg = *tlscfg
		conn, err = amqp.DialTLS(uriConfig.String(), newtlscfg)
		if err == nil {
			break
		}
	}
	return conn, err
}
```

**Comment by michaelklishin** [comment]
[It does](https://github.com/streadway/amqp/blob/master/connection.go#L196) but only in certain cases. I don't know if `tls.Config` is meant to be reused in general.

Failures come in different shapes and forms. You may want to clarify what exactly fails as hostname modification should be irrelevant if peer verification isn't used (or is not CN-based, for example).
