### ISSUE TITLE
How to specify payload encoding to base64?

### ISSUE THREAD

**Issue by kkzhang** [streadway/amqp#289]
I cannot found "payload encoding" in  params of Publising, did you miss it?

**Comment by michaelklishin** [comment]
[See this example](https://github.com/streadway/amqp/blob/2e25825abdbd7752ff08b270d313b93519a0a232/_examples/simple-producer/producer.go#L88).

**Comment by kkzhang** [comment]
Thanks very much.
But it is not what i referred to. It is content-encoding, not
payload-encoding. I want the payload stored in base64 format.
It finally solved by just passing bytes to rabbitmq, it is encoded
automatically!

My mistake. Thank u very much.

**Comment by michaelklishin** [comment]
@kkzhang RabbitMQ treats message payloads as opaque streams of bytes. You can pass anything you want for message body. The above link demonstrates how to set a message property that will communicate to other apps what the content encoding really is (it's up to the apps to make use of it, client libraries do not perform any automatic serialisation).
