### ISSUE TITLE
Breaking Change

### ISSUE THREAD

**Issue by brianpowell** [streadway/amqp#291]
# github.com/streadway/amqp
../../streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)
../../streadway/amqp/uri.go:76: u.Port undefined (type *url.URL has no field or method Port)

**Comment by michaelklishin** [comment]
See [Supported Go Versions](https://github.com/streadway/amqp#supported-go-versions).

**Comment by michaelklishin** [comment]
For those who cannot upgrade to Go 1.8 or 1.9:the change was introduced in #286. The most recent version that does not rely on `*url.URL#Hostname` is 08577bbc9535a8f693ff7f57631b1deac748fe8f, which includes #264 and likely can get you through several more months just fine.
