### ISSUE TITLE
 u.Hostname undefined

### ISSUE THREAD

**Issue by dprabhua** [streadway/amqp#292]
The "go get github.com/streadway/amqp" giving the below error

 github.com/streadway/amqp
/bms/webapps/jenkins/workspace/team_CloudCenter-Dev/go/src/github.com/streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)
/bms/webapps/jenkins/workspace/team_CloudCenter-Dev/go/src/github.com/streadway/amqp/uri.go:76: u.Port undefined (type *url.URL has no field or method Port)

**Comment by MaximeAtMyNotary** [comment]
Hi,

We have the same issue here.

**Comment by invokr** [comment]
What version of go are you using? I can reproduce this issue when using `go 1.7`, using `go 1.8` doesn't have this issue. 

I think the fields it's crying about were introduced in 1.8, which is the earliest support version according to the readme.

**Comment by dprabhua** [comment]
i am facing this issue in go1.6.2 linux/amd64

**Comment by MaximeAtMyNotary** [comment]
I was using `go 1.6`, it fine now with `go 1.9` :) Thanks

**Comment by dprabhua** [comment]
In go1.9, im getting this error

# github.com/streadway/amqp
flag provided but not defined: -goversion
usage: compile [options] file.go...

**Comment by dprabhua** [comment]
After setting the GOROOT its working fine for me. Thanks Guys

**Comment by michaelklishin** [comment]
Consider looking at recent issues before filing a new one: this is a duplicate of #292 filed hours earlier.
