### ISSUE TITLE
Version 1.6.2 of Go (Ubuntu 16.04 LTS) complains about Hostname and Port.

### ISSUE THREAD

**Issue by artyanikey** [streadway/amqp#294]
https://github.com/streadway/amqp/blob/cefed15a0bd808d13947f228770a81b06ebe8e45/uri.go#L75

/home/max/go/src/github.com/streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)
/home/max/go/src/github.com/streadway/amqp/uri.go:76: u.Port undefined (type *url.URL has no field or method Port)

While running:

go get github.com/streadway/amqp

**Comment by lukebakken** [comment]
Please see the responses to #291 and #292
