### ISSUE TITLE
why in the examples simple-producer have no queue declare and binding?

### ISSUE THREAD

**Issue by Anteoy** [streadway/amqp#297]
why the code in the examples simple-producer have no queue declare and binding? I try to run simple-producer at the first,at the end of the producer,I run simple-consumer,during the time,the message is losed.Only I run simple-consumer at first which have declare queue and binding can work.

**Comment by michaelklishin** [comment]
Publishers are discouraged from (or at least not required to) declaring queues unless they also consume. Consumers are supposed to do that.
