### ISSUE TITLE
No definition on Unacked count despite docs on QueueInspect

### ISSUE THREAD

**Issue by pyrat** [streadway/amqp#300]
https://github.com/streadway/amqp/blob/master/channel.go#L830

Unsure if the docs for this method `QueueInspect` are confusing me but it specifies that this method will allow you to inspect the number of Unacked messages in the queue.

But it doesnt operate like this. Would it be wasy to add?

**Comment by cesar0094** [comment]
Any help on this? Thanks!

**Comment by michaelklishin** [comment]
`queue.declare-ok` carries the number of messages in "ready" state, not unacknowledged ones. If you want to retrieve a broader set of queue metrics, use the HTTP API and https://github.com/michaelklishin/rabbit-hole/.
