### ISSUE TITLE
uri.go has errors when go get pulls code.

### ISSUE THREAD

**Issue by gnosthi** [streadway/amqp#301]
OS: Debian/ Sid
GO Version: go version go1.6.2 linux/amd64

When pull code I get the following errors. 

 go get -v -u github.com/streadway/amqp
github.com/streadway/amqp (download)
github.com/streadway/amqp
# github.com/streadway/amqp
../../../streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)
../../../streadway/amqp/uri.go:76: u.Port undefined (type *url.URL has no field or method Port)

These errors also occur when trying to build my project against the amqp library.

**Comment by terasum** [comment]
this problem was also occured when I `go get the github.com/streadway/amqp` today

**Comment by lukebakken** [comment]
Please see the responses to #291, #292 and #294.
