### ISSUE TITLE
github.com/streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)

### ISSUE THREAD

**Issue by elvin-du** [streadway/amqp#302]
cannot build,the error:
github.com/streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)

**Comment by lukebakken** [comment]
Your version of Go is too old.

Please see the responses to #291, #292, #294 and #301.

**Comment by thebriz24** [comment]
I'm running 1.9.2, and it's giving me the same problem.

**Comment by thebriz24** [comment]
<img width="638" alt="screen shot 2018-03-01 at 9 44 55 am" src="https://user-images.githubusercontent.com/14654329/36857262-4e400e36-1d35-11e8-9ee8-2a94cd587deb.png">
Struct from current documentation
