### ISSUE TITLE
encounter painc when dial

### ISSUE THREAD

**Issue by doubleceston** [streadway/amqp#303]
hi,
  when i try to init a rabbitmq conusmer, i first pass an url-address  fomat like this  

 "amqp://xxx_user:xxx@xxxxhostnamexxx:5672/xxx"

but painc in parse url 
 info :
      panic: parse "amqp://xxx_user:xxx@xxxxhostnamexxx:5672/xxx": first path segment in URL cannot contain colon

i have tried to search in codes to find what's going wrong
https://github.com/streadway/amqp/blob/master/uri.go 
func ParseUrl()and line 62

please point out the wrong place i have done

**Comment by lukebakken** [comment]
Hello,

I am unable to reproduce your issue - give it a try [here](https://play.golang.org/p/gJdrp7-Jgw)

There must be something special in your URL that you are not including in this issue. Can you provide more information? What version of Go are you using?
