### ISSUE TITLE
Consumer tags exceeding maximum allowed length are generated

### ISSUE THREAD

**Issue by deadok22** [streadway/amqp#306]
A consumer tag is generated when `Channel.Consume` is called with `consumer` set to empty string. The generated value may exceed maximum allowed length resulting in a [failure to map](https://github.com/streadway/amqp/blob/ff791c2d22d3f1588b4e2cc71a9fba5e1da90654/consumers.go#L122) `basicDeliver` messages back to consumers and ultimately [dropping messages without acks or nacks](https://github.com/streadway/amqp/blob/ff791c2d22d3f1588b4e2cc71a9fba5e1da90654/channel.go#L328).

Change the tag generator so that it never generates names exceeding maximum allowed length. See #305 for similar problems.

I didn't run integration tests yet, but I plan to submit a pull request with the fix: https://github.com/deadok22/amqp/commit/440a0930e2eaecd094302ce250a636aace65d8c4

**Comment by michaelklishin** [comment]
Please submit a PR.

**Comment by deadok22** [comment]
Pull request: #322
