### ISSUE TITLE
Connection closed but channel still open

### ISSUE THREAD

**Issue by sxllwx** [streadway/amqp#307]
Hi,

I think I've found a bug with channel.Close(): sometimes the call is blocked indefinitely.

My scenario:

I've wrote code, then create a connection . I start to consume on this queue.
Then I close the connection from the RabbitMQ web interface. Obviously, the connection and channel is closed. I  got message from  func (c *Connection) NotifyClose(receiver chan *Error) chan *Error, but I can't get any message from func (ch *Channel) NotifyClose(c chan *Error) chan *Error 。

**Comment by michaelklishin** [comment]
The [Go] channel you are looking for is for [AMQP 0-9-1] channel-level exceptions. After the connection is closed, there can be no further notifications for the [AMQP 0-9-1] channel.
