### ISSUE TITLE
deliveries breaks but I can't get something returned from NotifyClose

### ISSUE THREAD

**Issue by FX-HAO** [streadway/amqp#308]
> Continues deliveries to the returned chan Delivery until Channel.Cancel, Connection.Close, Channel.Close, or an AMQP exception occurs.

Should I reconnect to RabbitMQ server after breaking out of the loop of deliveries? My code is like the following:

```golang
for {
	conn, err := amqp.Dial(fmt.Sprintf("amqp://%s", AMQP.URI))
	if err != nil {
		log.Fatalf("Failed to connect to RabbitMQ, %v", err)
	}
	go func() {
		fmt.Printf("closing: %s", <-c.conn.NotifyClose(make(chan *amqp.Error)))
	}()

	ch, err := conn.Channel()
	if err != nil {
		log.Fatalf("Failed to open a channel, %v", err)
	}

	deliveries, err := ch.Consume(
		AMQP.QueueName, // queue
		"",             // consumer
		true,           // auto-ack
		false,          // exclusive
		false,          // no-local
		false,          // no-wait
		nil,            // args
	)
	if err != nil {
		return err
	}

	for delivery := range deliveries {
		handle(delivery)
	}
	log.Error("Connection terminates") // And I will get the error returned from c.conn.NotifyClose
}
```

Is something wrong?

**Comment by FX-HAO** [comment]
And I got a circumstance that the loop of `deliveries` instantly breaks after publishing a message to the queue every time. So if there are 10 messages in the queue, it will reconnect 10 times and take one every time.

**Comment by michaelklishin** [comment]
See [examples](https://github.com/streadway/amqp/tree/master/_examples) for an example of connection recovery.

Note that RabbitMQ deliveries will be put into a Go channel which may or may not have any messages at the time you iterate over it. How to deal with that should not be specific to this client.

Please consult server logs to gather additional information that might help your case.

**Comment by FX-HAO** [comment]
@michaelklishin What conditions the `range` that iterates over the `deliveries` breaks but get nothing returned from `conn.NotifyClose`
