### ISSUE TITLE
Message reception blocked if one goroutine fails

### ISSUE THREAD

**Issue by jaipradeesh** [streadway/amqp#313]
#### Main

```
..
..
..
	forever := make(chan *amqp.Delivery)

	// Init consumer

	// Declare queue
	initQueueDeclare, initQueueDeclareErr := centralChan.QueueDeclare(
		"init", // Queue name
		true,   // Durable
		false,  // Delete when used
		false,  // Exclusive
		false,  // No wait
		nil,    // Arguments

	)
	if initQueueDeclareErr != nil {
		log.Fatalln("Error declaring queue: init", initQueueDeclareErr)
	}

	// Bind queue
	initQueueBindErr := centralChan.QueueBind(
		"init",   // Queue name
		"init.*", // Routing key
		"dex",    // Exchange name
		false,    // No wait
		nil,      // Arguments
	)
	if initQueueBindErr != nil {
		log.Fatalln("Error binding queue: init", initQueueBindErr)
	}

	// Listen for messages to consume from queue
	initMessages, initConsumeErr := centralChan.Consume(
		initQueueDeclare.Name, // Queue name
		"",    // Consumer
		true,  // Auto ackowledge
		false, // Exclusive
		false, // No local
		false, // No wait
		nil,   // Arguments
	)
	if initConsumeErr != nil {
		log.Fatalln("Error registering consumer for queue: init", initConsumeErr)
	}

	// Listen for messages, parse, generate resources in turing
	go func() {
		for message := range initMessages {
			go makeHTTPRequest()
		}
	}()
       <- forever

..
..
..
```

#### makeHTTPRequest

``` 
..
..
	podReq, _ := http.NewRequest("GET", "http://example.com", nil)

	podRes, err := httpClient.Do(podReq)
	if err != nil {
		log.Println(err)
	}
	defer podRes.Body.Close()
	podBodyBytes, _ := ioutil.ReadAll(podRes.Body)
	log.Println(string(podBodyBytes))
..
..
```

- On every message, a function is spinned on a goroutine which makes a HTTP request and reads from response body.
- Since by default go's HTTP client doesn't have a timeout, in ideal scenario, if the HTTP request doesn't return anything forever, it should block only the goroutine.
- But RabbitMQ doesn't receive any message is one goroutine is hung forever.

**Comment by mathewvp** [comment]
Do you have prefetch enabled?

**Comment by jaipradeesh** [comment]
No. But that shouldn't be an issue. The exchange is not a heavy one and receives around 5-10 requests per minute.

**Comment by lukebakken** [comment]
Could you please try the following:

* Does adding a timeout to the HTTP request resolve the issue?
* If you replace the HTTP request with a long sleep, to simulate a rong-running request, do you see the issue?

**Comment by jaipradeesh** [comment]
Adding a timeout have resolved the issue, apparently. But could you guess why did it happen?

**Comment by jaipradeesh** [comment]
Update: Adding a timeout did not resolve the issue.

**Comment by michaelklishin** [comment]
Prefetch has nothing to do with how "loaded" an exchange is, [see the docs](http://www.rabbitmq.com/confirms.html).

The snippet consumes in automatic acknowledgement mode, though, so prefetch doesn't apply.

**Comment by michaelklishin** [comment]
@jaipradeesh we are huge fans of collecting data instead of guessing. Please take a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) of a reproduction and post it here.

**Comment by jaipradeesh** [comment]
@michaelklishin Sorry about that. The past instance did not have much logs/error handlers enabled. I've added the same in the application. Will close the issue for now and update when I find the root cause.
