### ISSUE TITLE
reconnection for publishers

### ISSUE THREAD

**Issue by magicalbanana** [streadway/amqp#314]
I've seen examples here on how to implement better reconnection when consuming. Does anyone now a good way or how would you handle reconnections with publishers?

**Comment by michaelklishin** [comment]
Largely the same way. The only difference is that you need to pay attention to the attempted publishes and the what delivery tags were confirmed. Note that when you open a new channel, delivery tag counter will be reset.

**Comment by alues** [comment]
It will be wonderful feature if connector can recover itself. @michaelklishin
