### ISSUE TITLE
Pub/Sub no error thrownwhen consumer stops connection to publisher

### ISSUE THREAD

**Issue by Yanaro** [streadway/amqp#317]
I follow the [https://www.rabbitmq.com/tutorials/tutorial-four-go.html](toturial) to create consumers to receive notifications, but after a while consumer would stop receiving messages from publisher (publisher is still working when I test with rabbitMQ local client)

**Comment by lukebakken** [comment]
I tested both tutorial three and tutorial four golang code from this repository and it worked as expected -
 https://github.com/rabbitmq/rabbitmq-tutorials

Could you please attach all of the code you are using?

**Comment by Yanaro** [comment]
@lukebakken This is the code I use, I think it's pretty much the tutorial code. It works as expected, at least for a few days. Afterwards it will no longer receive any message from rabbitMQ publisher
`func Receive (hub *socket.Hub, queueHost string, queuePort string, queueUser string, queuePass string) {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
	var connectionString = rabbitMQUri(queueHost, queuePort, queueUser, queuePass)
	var conn, err = connectToRabbitMQ(connectionString)

	defer conn.Close()

	ch, err := conn.Channel()
	failOnError(err, "Failed to open a channel")
	defer ch.Close()

	err = ch.ExchangeDeclare(
		exchangeName,   // name
		exchangeType, // type
		false,     // durable
		false,    // auto-deleted
		false,    // internal
		false,    // no-wait
		nil,      // arguments
	)
	failOnError(err, "Failed to declare an exchange")

	q, err := ch.QueueDeclare(
		"",    // name
		false, // durable
		false, // delete when usused
		true,  // exclusive
		false, // no-wait
		nil,   // arguments
	)
	failOnError(err, "Failed to declare a queue")

	err = ch.QueueBind(
		q.Name, // queue name
		queueKey,     // routing key
		exchangeName, // exchange
		false,
		nil)
	failOnError(err, "Failed to bind a queue")

	msgs, err := ch.Consume(
		q.Name, // queue
		"",     // consumer
		true,   // auto-ack
		false,  // exclusive
		false,  // no-local
		false,  // no-wait
		nil,    // args
	)
	failOnError(err, "Failed to register a consumer")
	forever := make(chan bool)

	go func() {
		for d := range msgs {
			log.Println("Received a message")
			data:= make(map[string]interface{})
			err := json.Unmarshal(d.Body, &data)
			if err != nil {
				data = map[string]interface{}{"message": string(d.Body), "type" : "update_data"}
				log.Printf("Error when decoding a message from queue: %s", err)
			}
			sendQueuedMessage(hub, data)
		}
	}()


	log.Printf(" [*] Waiting for messages. To exit press CTRL+C")
	<-forever
	log.Printf("Disconnected from rabbitMQ")
}`

**Comment by lukebakken** [comment]
* How are you publishing messages?
* Could you please provide _complete_, self-contained producer code and consumer code that can be run via `go run`? The people who help maintain this library do so when they have free time so anything you can do to speed up diagnosis is appreciated a lot.

> It works as expected, at least for a few days. Afterwards it will no longer receive any message from rabbitMQ publisher

* How many messages are published over this period of time? At what rate?
* Do you see any errors in the RabbitMQ logs?
* When this code no longer receives messages, is the consumer still listed in RabbitMQ? You can check by running `rabbitmqctl list_consumers`

**Comment by michaelklishin** [comment]
The answer here can be as simple as: in a few days your client loses connection to RabbitMQ and does not perform recovery (which is by design a manual step with this client).
