### ISSUE TITLE
No lock in ack/nack

### ISSUE THREAD

**Issue by svarogg** [streadway/amqp#318]
Is there a reason why there's no call for ch.m.lock() in .Ack() and .Nack(), the same way there's in .Publish() etc?

This causes .Ack() and .Nack() to be non-thread safe?

**Comment by michaelklishin** [comment]
Probably just a an oversight. Both `basic.publish` and `basic.{ack,nack}` have a lot of similarities in the protocol (e.g. they don't have a response), and so are their concurrency "characteristics". Please submit a PR and we will discuss.
