### ISSUE TITLE
Exception (403) Reason: "username or password not allowed"

### ISSUE THREAD

**Issue by soniabhishek** [streadway/amqp#320]
I am getting this error on my localhost 
the following code I have used 
`
                         conn, err := amqp.Dial("amqp://" + username + ":" + password + "@" + host + ":5672/")
			if err != nil {
				log.Fatalf("cannot (re)dial: %v: %q", err, username)
			}`

on checking the rabbitmq logs I found these error messages

> =ERROR REPORT==== 7-Mar-2018::19:45:13 ===
closing AMQP connection <0.2237.0> (127.0.0.1:59412 -> 127.0.0.1:5672):
{handshake_timeout,frame_header}

> =ERROR REPORT==== 7-Mar-2018::19:45:33 ===
closing AMQP connection <0.2165.0> (127.0.0.1:59399 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 10s

According to my observation, this only occurs when I am using the **debugger** 

I am currently using **Intellij IDE** debugger is there any special line of code I need to add so that this connection should not break anywhere or is there any issue in the library. 

This seems to be very easily reproducible on my local and never occur in normal execution. (only occur when i use debug mode)

**Comment by michaelklishin** [comment]
Debuggers can pause program execution. RabbitMQ assumes connections complete the handshake in 10 seconds by default. The log clearly states that wasn't the case with your client, very likely because it was paused.

**Comment by soniabhishek** [comment]
Thanks @michaelklishin for your reply, It was clear from your answer that it was because of the pause in code execution. But I have few questions
1) This Dial code runs to get the new connection; even though I paused the execution, when I continue it should create a new connection without a hassle. 

2) What should be my go around for this I have this connection creation code in my init() function and a lot dependent upon debuggers for testing but because of this issue I am not been able to continue execution.
