### ISSUE TITLE
There is any way to set max buffer size for consume?

### ISSUE THREAD

**Issue by Vetcher** [streadway/amqp#325]
As I see [here](https://github.com/streadway/amqp/blob/master/consumers.go#L40), input channel eats everything, until app has enough memory to buffer messages. So, my question is: how can I limit buffer size (or length)? Can lib do this automatically, or I should write some logic?

**Comment by michaelklishin** [comment]
Using [channel QoS](http://www.rabbitmq.com/confirms.html).
