### ISSUE TITLE
 Excessive processing time causes channel failure

### ISSUE THREAD

**Issue by zuston** [streadway/amqp#326]
when i consume the data, i found that the channel fails. maybe because of saving the data time too long. my code binding channel is blocking ,but the rabbitmq queue data is remaining much.
please give me some suggestions.

**Comment by zuston** [comment]
ok, i find the solution . https://stackoverflow.com/questions/35438843/rabbitmq-error-timeout.
should set the channel qos

**Comment by michaelklishin** [comment]
[Relevant documentation guide](https://www.rabbitmq.com/confirms.html).

**Comment by zuston** [comment]
Thanks!
