### ISSUE TITLE
Delivery.Timestamp is "0001-01-01 00:00:00 +0000 UTC" ever time

### ISSUE THREAD

**Issue by muratsplat** [streadway/amqp#328]
Hello,

I  try to get date time of regarding message is provided by RabbitMQ. But the date time is not correct very time. This is bug or I missed a point on here ?

```go

	msgs, err := ch.Consume(
		conf.GetNameOfQueue(),    // queue
		conf.GetNameOfConsumer(), // consumer
		false, // auto-ack
		false, // exclusive
		false, // no-local
		false, // no-wait
		nil,   // args
	)

	go func() {
		for d := range msgs {
			log.Info(d.Timestamp.String()) // "0001-01-01 00:00:00 +0000 UTC"
		}
	}()
```

**Comment by michaelklishin** [comment]
We cannot tell since you haven't shared any publisher code. [Wireshark can reveal](http://www.rabbitmq.com/amqp-wireshark.html) what's being sent by RabbitMQ, which would be extremely valuable to have when investigating this.
