### ISSUE TITLE
Failed to get queue length for queue

### ISSUE THREAD

**Issue by vdoodala** [streadway/amqp#332]
I am getting following error -

Failed to get queue length for queue example: parse 'amqp://username:password@hostname:5672//': first path segment in URL cannot contain colon

How to resolve the issue?? Any inputs ???

**Comment by xReprisal** [comment]
I have tried exactly the same format as you (including trailing slashes) and it worked. Can you possibly produce simple test where this eroor occurs?

**Comment by michaelklishin** [comment]
Please provide an executable example, there isn't enough information to work with in this issue.
