### ISSUE TITLE
Deadlock when in confirm mode.

### ISSUE THREAD

**Issue by xReprisal** [streadway/amqp#333]
I'm running into deadlock on producer when channel is in confirm mode.

I think it has to do with `confirms.go`  mutex around [published](https://github.com/streadway/amqp/blob/master/confirms.go#L31) property. When I alter this property to be `atomic.Uint64` using go.uber.org/atomic package issue is solved. 

```
package amqp

import (
	"sync"
	"fmt"
	"go.uber.org/atomic"
)

// confirms resequences and notifies one or multiple publisher confirmation listeners
type confirms struct {
	m         sync.Mutex
	listeners []chan Confirmation
	sequencer map[uint64]Confirmation
	published *atomic.Uint64
	expecting uint64
}

// newConfirms allocates a confirms
func newConfirms() *confirms {
	return &confirms{
		sequencer: map[uint64]Confirmation{},
		published: atomic.NewUint64(0),
		expecting: 1,
	}
}
...
// publish increments the publishing counter
func (c *confirms) Publish() uint64 {
	c.published.Inc()
	return c.published.Load()
}
```

I can create test if this does not convey the problem clearly.

**Comment by michaelklishin** [comment]
@xReprisal that code does acquire a lock but we'd consider a PR that switches to an atomic data type. A test that runs a reasonably long time and allows to reproduce would be appreciated. Thanks.

**Comment by xReprisal** [comment]
I think I've finally realized my issue. I was doing something along these lines:
```

func (p *Producer) run() {
	for {
		select {
		case <-p.confirm:
			// logic goes here
		case msg := <-p.publish:
			if err := p.ch.Publish(p.exchangeName, p.routingKey, true, false, msg); err != nil {
				// logic goes here
			}
		}
	}
}

func (p *Producer) Publish(msg samqp.Publishing) {
	p.publish <- msg
}
```

Seems like the problem was with listening to both `p.publish` and `p.confirm` on the same select statement. When I moved `p.confirm` outside there are no deadlocks.
