### ISSUE TITLE
uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname), go v1.9.6

### ISSUE THREAD

**Issue by kayh-de** [streadway/amqp#335]
Hi guys,
unfortunately is experienced the issue as already discussed in several other issues before.

Current Go version, but the 1.10.x also does not work... :(
```
go version go1.9.6 linux/amd6
```

I made the "hack" in the uri.go file and it is working:
```
	host := "localhost"
	port := "5672"
```

What did I wrong? 

My proposal: Supported versions should either be updated or this host/port thing should be initialized on another proper way.

Many Thanks in advance.

Regards,
Kay

**Comment by lukebakken** [comment]
Please provide a PR with tests! Thanks.

**Comment by kayh-de** [comment]
Hi there,

yes. I can do.

**Comment by kayh-de** [comment]
Hi,
I tried to reproduce the issue. However, it seems not occurring anymore. 

Let me close this issue for now. If it comes up again, I can re-open it.

**Comment by michaelklishin** [comment]
Duplicate of #302 and a bunch of other issues.
