### ISSUE TITLE
How to connect to RabbitMQ cluster?

### ISSUE THREAD

**Issue by teran** [streadway/amqp#339]
Hello,

I have three nodes of RabbitMQ in cluster and want use them properly according to [docs](https://www.rabbitmq.com/clustering.html#clustering-and-clients) but I cannot find any mentions of how to specify their FQDNs properly, it there a way to use clustered RabbitMQ at all?

Thanks in advance.

**Comment by lukebakken** [comment]
Did you look at the [example code](https://github.com/streadway/amqp/tree/master/_examples)?

Your application will have to choose a node in your cluster and connect to it with this library. If an un-recoverable connection error or other error occurs, your application will have to choose another node and connect to it. `streadway/amqp` does not provide that for you.

**Comment by teran** [comment]
@lukebakken huh, so `streadway/amqp` doesn't handle clustered RabbitMQ backends, thanks!

**Comment by lukebakken** [comment]
Some AMQP clients support that (like the RabbitMQ Java client), but most don't and leave "higher level" operations like that up to the application developer or to another library (like EasyNetQ for .NET).

With enough demand and volunteer time, this library could support that as well. Another option is to use haproxy to round-robin connections.

**Comment by sirius1024** [comment]
@teran 
Try this extension with reconnect and cluster supported:
https://github.com/sirius1024/go-amqp-reconnect
