### ISSUE TITLE
Dial multiple addr

### ISSUE THREAD

**Issue by pathbox** [streadway/amqp#341]
Hi,
    I have a question, how to dial multiple addr, yes, I can do it by my code, I just want to know if `amqp` support it

**Comment by lukebakken** [comment]
Have you looked at the code in this project yourself?

**Comment by pathbox** [comment]
@lukebakken  Yes, as we konw, `Dial(url string)` , it can not be `Dial(url []string{})`

**Comment by lukebakken** [comment]
Great, you answered your own question. This project would welcome a PR that implements the feature if you would like to submit one with tests.

**Comment by michaelklishin** [comment]
A PR that adds support for multiple URIs/endpoints would be welcome. It is reasonably easy to do that without special support in this client.

**Comment by HiranyaKavishani** [comment]
Hi @michaelklishin, does the client now supports for multiple uris/endpoints?
