### ISSUE TITLE
manual Ack does not work after first message

### ISSUE THREAD

**Issue by mantzas** [streadway/amqp#342]
hi,

i have setup a "consumer" for a rabbitmq queue. Every delivery is put in a channel which is picked up by a goroutine in order to be processed.
After processing the delivery is then Ack or Nack based on the success of the processing.
It seems that the first one is processed ok but the rest cannot be Ack/Nack.
The ui of rabbitmq shows every message in a unacked state, which probably means that the consumer gets the message from the queue but something prevents it for being put in the above mentioned channel for processin.

The consume part of the queue can be found here : https://github.com/mantzas/patron/blob/amqp-lock/async/amqp/amqp.go
The processing goroutine can be found here: https://github.com/mantzas/patron/blob/amqp-lock/async/component.go

Does anybody have a idea?

**Comment by michaelklishin** [comment]
This is mailing list material (rabbitmq-users). A [traffic capture](http://www.rabbitmq.com/amqp-wireshark.html) can clearly tell whether any acknowledgements were sent by the client. Reducing your code to a smaller and smaller reproducible case would help immensely.

**Comment by mantzas** [comment]
thanks i will go to the mailing list then after i get a capture.
