### ISSUE TITLE
Unable to override channel_max in the rabbitmq client config with a value larger than the server config

### ISSUE THREAD

**Issue by AgrimPrasad** [streadway/amqp#346]
After the changes in https://github.com/rabbitmq/rabbitmq-server/issues/1593 the rabbitmq server side limit for the maximum number of channels per connection by default has been lowered to 2047.

This library followed up by using the same value (2047) as the `defaultChannelMax ` value in https://github.com/streadway/amqp/commit/f34b892a098e4d53e83bce0ba35cbdc8c3fc4a5a

It's mentioned in the above commit that `rare applications that need more channels per connection can still override the value`. Unfortunately, I tried to override this value as follows, but the final `channel_max` value still ended up being 2047.

```
amqp.DialConfig(url, amqp.Config{
			Heartbeat:       10 * time.Second,
			TLSClientConfig: amqpsConfig, // irrelevant to issue
			Locale:          "en_US",
			ChannelMax:      2047 * 2,
		})
```

By adding some debug logs locally, I'm able to see that the library currently picks the minimum of client side and server side configured values, which means that if the client config has `ChannelMax` > 2047 then the final value picked will still be 2047:

https://github.com/streadway/amqp/blob/70e15c650864f4fc47f5d3c82ea117285480895d/connection.go#L759

and 

https://github.com/streadway/amqp/blob/70e15c650864f4fc47f5d3c82ea117285480895d/connection.go#L837-L842

The pick function should be modified to pick the **maximum**, rather than the minimum of client and server `ChannelMax` config.

**Comment by AgrimPrasad** [comment]
@michaelklishin Tagging you for attention since the changes in https://github.com/streadway/amqp/commit/f34b892a098e4d53e83bce0ba35cbdc8c3fc4a5a were implemented by you recently, thanks!

**Comment by lukebakken** [comment]
> The pick function should be modified to pick the maximum

Why? If you were to exceed the value configured in RabbitMQ, the broker would close the channel (so channel 2048, 2049, etc etc). A client can't override the maximum specified in RabbitMQ.

**Comment by michaelklishin** [comment]
Obviously clients are not supposed to use higher limits that the server was configured to allow for.
