### ISSUE TITLE
ExternalAuth type and interface definition

### ISSUE THREAD

**Issue by damianjaniszewski** [streadway/amqp#355]
This is more like a feature request than issue. I would like to suggest to define ExternalAuth type similar to already defined PlainAuth. When using TLS and client certificate it is required to return authentication mechanism EXTERNAL so the username will be taken from certificate. Defining the type and providing example in godoc.org reference will help users who try to authenticate with client certificate.

It could be something similar to:

```
type ExternalAuth struct {
}

func (auth *ExternalAuth) Mechanism() string {
  return "EXTERNAL"
}

func (auth *ExternalAuth) Response() string {
  return ""
}
```

**Comment by michaelklishin** [comment]
I believe this was addressed in master.

**Comment by treksler** [comment]
does not appear to be implemented in https://github.com/streadway/amqp/blob/master/auth.go

and does not appear to be documented in https://godoc.org/github.com/streadway/amqp

**Comment by lukebakken** [comment]
@treksler this project's maintainers (who do so on a volunteer basis) would happily review a pull request that implements this feature. Even better if the PR includes tests.

**Comment by treksler** [comment]
see #121

**Comment by lukebakken** [comment]
@treksler thanks for pointing that out. That PR is stale as the original submitter did not make the requested changes in the discussion. You could take the work in that branch and submit your own pull request that implements what was requested in these comments:

* [Request to add a regression test](https://github.com/streadway/amqp/pull/121#issuecomment-59500622)
* [Use `ExternalAuth` as the struct name](https://github.com/streadway/amqp/pull/121#issuecomment-268991634)
* [Avoid `Dial*` function explosion by adding parameters / options instead](https://github.com/streadway/amqp/pull/121#issuecomment-262957960)
