### ISSUE TITLE
HEAP Explodes Under heavy load 

### ISSUE THREAD

**Issue by zacharyestep** [streadway/amqp#356]
http://www.rabbitmq.com/tutorials/tutorial-three-go.html

I've been debugging some golang code I maintain that uses this library to spin up golang consumers for rabbitmq. 

It seems that the amqp.Delivery is always allocated on the heap in my runtime and golang never gets around to free()'ing them. 

To test my sanity I hooked up the example log-file consumer here to a heavily overloaded rabbitmq bus - and just like my more complex examples the VIRT/RES shoots up linearly overruntime until the program crashes. Is this normal/expected behavior or something I can tune with rabbitMQ? 

I'm running on RHEL6.10 using Golang 1.9+.  I pulled the heap profile using PPROF and saw 98% in amqp.Delivery from the recvCon(method. Similar for the example consumer. 

V/r,

**Comment by lukebakken** [comment]
It would be great to provide code and exact reproduction / diagnosis steps for people like me who aren't as familiar with profiling tools. Or, a PR with a fix. Anything you can do to reduce the amount of time maintainers have to guess and write code to try and reproduce what you report is greatly appreciated.

**Comment by zacharyestep** [comment]
https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/go/receive_logs.go

If you compile this and run it under heavy load, the heap explodes even if you pipe output to /dev/null. 

Is this normal? I've compiled with pointer analysis on, and I notice that when reading from the consumer channel the local variable for the delivery is ALWAYS ESCAPING TO THE HEAP. 
If I modify the code somewhat to keep the local delivery variable from escaping , the heap doesn't grow out of control and the memory profile stays flat - say by changing to loggin the length of the ContentType instead of the whole boddy.

**Comment by zacharyestep** [comment]
https://play.golang.org/p/0aS4X9LaTQ3

**Comment by zacharyestep** [comment]
https://github.com/carbonblack/cb-event-forwarder/blob/master/test/stress_rabbit/stress_rabbit.py

**Comment by zacharyestep** [comment]
(Above is a sample of the code i'm using to test the consumer and the stressor I use to dump messages onto rabbit MQ)

**Comment by lukebakken** [comment]
> ALWAYS ESCAPING TO THE HEAP.

There's no need to use all caps.

The tutorial code does not set a QoS (prefetch) value, so there is no limit on the number of messages that RabbitMQ will try to send to it. Go's GC may not be able to keep up, or there may be an issue in this library where the buffer used for the message body isn't managed correctly.

I suspect that changing the tutorial code to use QoS and to *not* use auto-ack would mitigate this issue. This would require sending an ack within the `for...range` loop.

**Comment by zacharyestep** [comment]
Thanks luke :) I tried adding a select-default to see if the consuming queue stays empty/full under runtime and it was staying pretty empty. I'll try this and report back.

**Comment by zacharyestep** [comment]
I modified 'util.go' above from the playground above , to force manual acking of the messages.
This did not change my results, at all. What QoS parameters are relevant? 
22252 bit9qa    20   0  279m  10m 2184 S 148.1  0.1   0:06.52 util   
# command-line-arguments
./util.go:11:28: msg escapes to heap
./util.go:9:33: leaking param: msg
./util.go:11:28: err escapes to heap
./util.go:9:33: leaking param: err
./util.go:11:27: failOnError ... argument does not escape
./util.go:66:12: func literal escapes to heap
./util.go:66:12: func literal escapes to heap
./util.go:64:24: main make(chan bool) does not escape

# command-line-arguments
./util.go:11:28: msg escapes to heap
./util.go:9:33: leaking param: msg
./util.go:11:28: err escapes to heap
./util.go:9:33: leaking param: err
./util.go:11:27: failOnError ... argument does not escape
./util.go:66:12: func literal escapes to heap
./util.go:66:12: func literal escapes to heap
./util.go:68:48: d.Body escapes to heap
./util.go:64:24: main make(chan bool) does not escape
./util.go:68:35: main.func1 ... argument does not escape
22288 bit9qa    20   0 2903m 2.7g 2180 S 167.5 17.2   0:14.34 util                                                                                                                                          

The difference in these two runs, is that I commented out the multivaradic function that escapes the delivery in the second. Are there relevant unit tests for this library that exercise this function? 

I'll add the pprof to the goplayground shortly.

**Comment by michaelklishin** [comment]
That's the documented trade-off betweeen [manual and automatic acknowledgement modes](http://www.rabbitmq.com/confirms.html): the higher the prefetch, the higher will peak consumer memory consumption but also higher the throughput ([up to a point](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/)).
