### ISSUE TITLE
int as Table value / validation error

### ISSUE THREAD

**Issue by huehnerhose** [streadway/amqp#363]
Hi,

I tried to use an `int` as header in an amqp message via the `Table`type. 
This resulted in a validation error claiming the type `int` isn't supported, at least when the value was `0`. A look into the `types.go@validateField` function `int` isn't in the list, but `int16/32/64` are. 

As far as I understood `int` in go, it's at least equivalent to `int32`, also it isn't  an alias. But from the standpoint of mapping an integer datatype into the amqp message, I don't understand why it should be banned. 

Is this an error or an active decision, if the later can you elaborate this decision (and maybe add a comment to the `Table` type)

Thanks!

**Comment by michaelklishin** [comment]
Please submit a PR that whitelists `int`. I don't see any reason not to treat it as `int32`.

**Comment by asahaf** [comment]
`int` need to be white listed in both `validateField` in file types.go and `writeField` in write.go

**Comment by asahaf** [comment]
in the fix `int` is treated as `int32`
