### ISSUE TITLE
Seemingly high cpu usage 

### ISSUE THREAD

**Issue by jpastoor** [streadway/amqp#364]
While doing a test with a message rate of about 500 messages / second I noticed a very high CPU usage. (In respect to another experiment in PHP with the same load).

I compiled with go version go1.10.1, streadway/amqp 70e15c650864f4fc47f5d3c82ea117285480895d to linux/amd64. The go application takes about 35% cpu and the PHP application 7%.

```
package main

import (
	"fmt"
	"github.com/streadway/amqp"
)

func main() {
	mq := fmt.Sprintf("amqp://%s:%s@%s:%d/", "user", "pwd", "host", 5672)
	conn, err := amqp.Dial(mq)
	if err != nil {
		panic(err)
	}
	ch, err := conn.Channel()
	if err != nil {
		panic(err)
	}

	deliveries, err := ch.Consume("queue", "demo", true, false, false, false, nil)
	if err != nil {
		panic(err)
	}

	for d := range deliveries {
		_ = d
	}
}
```

Profiling output:
![cpu](https://user-images.githubusercontent.com/733306/47853008-bc368280-dddd-11e8-9880-1f5cece9cf5e.png)

Any thoughts about this? Thanks in advance!

**Comment by mathewvp** [comment]
Is the sample code running with auto acknowledge enabled?

**Comment by jpastoor** [comment]
Thanks for your responses @virmundi @mathewvp 

Both PHP and Go have autoack enabled and run on a continuous even load of 500 msg / second.

**Comment by michaelklishin** [comment]
Your PHP app is likely both single threaded and less efficient. 35% is hardly high CPU usage given that this client can saturate multiple cores quite a bit higher if your consumer is concurrent and the stream of deliveries is sufficiently high.

I don't see any outliers in this client's code. "External code" possibly means network I/O? and a futex is a kernel data structure used internally by the runtime.
