### ISSUE TITLE
Need help on the best way to use amqp for RabbitMQ

### ISSUE THREAD

**Issue by RachitKansal** [streadway/amqp#366]
So I have a gorilla mux http router for serving HTTP requests. I am exposing rabbitMQ via HTTP POST from this router. Now i'm running into the following issue: **channel id space exhausted**, even though I close the channel used for publishing. **I am performing a stress test on my API, where I hit the POST endpoint with 1500 requests/second.**

My POST request handler calls the following code:
` 

	payload := models.PublishMessageResponse{}

	// Iterating over the list of all messages
	log.Println("publishing the messages to the internal queue")
	for index, requestElement := range params.PublishBody.PayloadList {

		// Getting the required routing key from the given parameters
		routingKey := utils.GetRoutingKeyFromFilter(*requestElement.TenantID,
			*requestElement.ServiceID, *requestElement.EntityType,
			*requestElement.OperationType)

		var message string
		var statusCode string

		log.Println("creating RMQ channel for the discovered RMQ")
		ch, err := registry.DiscoverRMQ().Channel()
		if err != nil {
			message = "Failed to create RMQ Channel"
			log.Println(fmt.Sprintf("%s: %s", message, err))
			statusCode = "301"
			failFlag = true
		} else {
			log.Println("RMQ channel created successfully, now publishing the message")
			err = ch.Publish(
				registry.GetRegistry().RMQConnectionMap[registry.DiscoverRMQ()].ExchangeTopicName,
				routingKey,
				false,
				false,
				amqp.Publishing{
					ContentType: "text/plain",
					Body:        []byte(*requestElement.Payload),
				})
			log.Println("publish operation completed")
			if err != nil {
				message = "Failed to push to RMQ Channel"
				log.Println(fmt.Sprintf("%s: %s", message, err))
				statusCode = "301"
				failFlag = true
			} else {
				log.Println("Message Published?")
				message = "Message Published Successfully"
				statusCode = "200"
			}
			errCh := ch.Close()
			if errCh != nil {
				log.Println("channel closed is in error: ", errCh)
			}
		}

		// Creating the response object for a single message
		log.Println("creating response for message:", index+1)
		singleResponse := models.MessageResponseObject{}
		singleResponse.Message = &message
		singleResponse.Status = &statusCode
		payload.ResponseList = append(payload.ResponseList, &singleResponse)`

So for each POST request I open a channel on the connection to RabbitMQ and then close the channel once the request is published to the exchange.

Am I doing anything wrong here? Any kind of help would be much appreciated

**Comment by RachitKansal** [comment]
but aren't a total of 65535 channels allowed to be open?

**Comment by lukebakken** [comment]
Please close this issue and continue the discussion [here](https://groups.google.com/d/topic/rabbitmq-users/SVUPmIzeuX8/discussion). This behavior is not due to a bug in `streadway/amqp`, so we'd prefer that discussion take place elsewhere. Thanks!

**Comment by RachitKansal** [comment]
Closing the issue here, taking the discussion up in the group.
