### ISSUE TITLE
publish lose data when reconnect the connection

### ISSUE THREAD

**Issue by michael1589** [streadway/amqp#370]
There're 2 goroutines, one just publish message and the other shutdown linux network, sleep more than 3 times of heartbead time(like 200s, and the heartbead time is 60s), reconnect server again. It triggers an error "Exception (501) Reason: "read tcp 172.16.16.132:56920->192.168.167.169:5672: i/o timeout"" in the previously registered channel by "conn.NotifyClose(receiver chan *Error) chan *Error" During the sleep time. I got less messages from rabbitmq server. I wonder why conn.send returns success but actually send fail. 
Deep into conn.send, bufio.Write and Flush will return no error. Is there a method to know I publish OK?

**Comment by vidmed** [comment]
The same issue for me. I can provide some code pieces to dive into the problem.

**Comment by michaelklishin** [comment]
Because publishing is an entirely asynchronous operation in the protocol and even a write that the OS has confirmed can fail to reach the server. Use [publisher confirms](https://www.rabbitmq.com/confirms.html).
