### ISSUE TITLE
RabbitMQ connection isClosed() should be public

### ISSUE THREAD

**Issue by RachitKansal** [streadway/amqp#376]
RabbitMQ connection isClosed() function is currently private and cannot be used externally to check whether the connection is still open or closed. Most clients in other languages do provide the functionality as a public function and hence should also be exposed by the go-client.

Google Group Discussion: https://groups.google.com/forum/#!topic/rabbitmq-users/x6oGr07nm8k

**Comment by gm42** [comment]
I agree with this; there is currently an issue where calling `Close()` on the connection you can receive an error about it being already closed (even if it was never explicitly closed).
