### ISSUE TITLE
NotifyReturn sends infinite amout of Returns with zero ReplyCode

### ISSUE THREAD

**Issue by justanotheruser** [streadway/amqp#377]
Seems like NotifyReturn works well with mandatory and not immediate publishing, but wrong with non-mandatory immediate.
I use next setup of cluster with 2 nodes (don't know if it's relevant):

```
docker network create rabbit
docker run -d --network rabbit --name rabbit1 \
  -p "5672:5672" -p "15672:15672" \
  -e RABBITMQ_NODENAME="rabbit@rabbit1" \
  -e RABBITMQ_ERLANG_COOKIE="adfsder" \
  rabbitmq:alpine

docker exec rabbit1 rabbitmq-plugins enable rabbitmq_management
docker exec rabbit1 rabbitmqctl stop_app
docker exec rabbit1 rabbitmqctl reset
docker exec rabbit1 rabbitmqctl start_app
docker exec rabbit1 rabbitmqctl add_vhost xyz
docker exec rabbit1 rabbitmqctl set_permissions -p xyz guest ".*" ".*" ".*"

docker run -d --network rabbit --name rabbit2 -e RABBITMQ_NODENAME="rabbit@rabbit2" -e RABBITMQ_ERLANG_COOKIE="adfsder" rabbitmq:alpine

docker exec rabbit2 rabbitmq-plugins enable rabbitmq_management
docker exec rabbit2 rabbitmqctl stop_app
docker exec rabbit2 rabbitmqctl reset
docker exec rabbit2 rabbitmqctl start_app
docker exec rabbit2 rabbitmqctl stop_app
docker exec rabbit2 rabbitmqctl join_cluster rabbit@rabbit1
docker exec rabbit2 rabbitmqctl start_app
```
Queue is created on rabbit2, my app connects to rabbit1.
Queue declaration:
```
returns := myChannel.NotifyReturn(make(chan amqp.Return, 1))
go func() {
	for {
		returned := <-returns
		fmt.Printf("Returned: %#v\n", returned)		
	}
}()
QueueDeclare(myQueueName, true, false, false, false, nil)
```
After I publish message with 
`myChannel.Publish("", myQueueName, false, true, msg)`
I see infinite stream of

> Returned: amqp.Return{ReplyCode:0x0, ReplyText:"", Exchange:"", RoutingKey:"", ContentType:"", ContentEncoding:"", Headers:amqp.Table(nil), DeliveryMode:0x0, Priority:0x0, CorrelationId:"", ReplyTo:"", Expiration:"", MessageId:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Type:"", UserId:"", AppId:"", Body:[]uint8(nil)}
> Returned: amqp.Return{ReplyCode:0x0, ReplyText:"", Exchange:"", RoutingKey:"", ContentType:"", ContentEncoding:"", Headers:amqp.Table(nil), DeliveryMode:0x0, Priority:0x0, CorrelationId:"", ReplyTo:"", Expiration:"", MessageId:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Type:"", UserId:"", AppId:"", Body:[]uint8(nil)}

I checked https://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.reply-code and haven't found zero value. What's happening?
Thanks.

**Comment by jspdown** [comment]
I having the issue when `immediate` is true. No matter if `mandatory` is true or false.

**Comment by michaelklishin** [comment]
RabbitMQ has stopped supporting the `immediate` flag years ago in 3.0. It returns an error when a client attempts to use it. The solution is not to use that property.

**Comment by michaelklishin** [comment]
Arguably this client could return an error when it is used. We'd definitely consider a PR for that, even given this client's extreme stance of backwards incompatible changes :(
