### ISSUE TITLE
Potential goroutine leak

### ISSUE THREAD

**Issue by jaipradeesh** [streadway/amqp#378]
pprof info

```
20 @ 0x42febb 0x43febd 0x863fc7 0x45df91
#	0x863fc6	github.com/foo/bar/vendor/github.com/streadway/amqp.(*Connection).heartbeater+0x186	/go/src/github.com/foo/bar/vendor/github.com/streadway/amqp/connection.go:546
```

**Comment by lukebakken** [comment]
This isn't nearly enough information. To start, code to reproduce this would be helpful to have.

**Comment by michaelklishin** [comment]
This is not evidence of a leak. To demonstrate a leak you have to run the code continuously and observe an ever growing number of goroutines. Your own code creates a goroutine, for example.

We are not aware of any outstanding issues with leaks so please provide a bit more evidence than this example.
