### ISSUE TITLE
ack a delivery on different channel than the one it's received through doesn't return error

### ISSUE THREAD

**Issue by asahaf** [streadway/amqp#381]
In RabbitMQ, delivery tags are scoped per channel. Ack a delivery on different channel than the one it's received through causes precondition_failed  "unknown delivery tag" exception. Although RabbitMQ raises this exception on the server, the return error on the client is `nil`

**Comment by asahaf** [comment]
Is that because ack is asynchronous?

**Comment by michaelklishin** [comment]
It's because channel error notifications are asynchronous in the protocol.
