### ISSUE TITLE
Example: Connection not closed if channel exception is not connection exception

### ISSUE THREAD

**Issue by Raqbit** [streadway/amqp#390]
The [Example](https://github.com/streadway/amqp/blob/1fcab46dce7d4148a84fc6eb15898f6865c7df6f/example_client_test.go#L88) uses `NotifyClose()` on the channel to detect when a connection/channel exception occurs, then reconnects to RabbitMQ & recreates the channel. By doing this it depends on the broadcasting of connection exceptions to all channel exception listeners.

Now, I might be missing something here, but if an _actual_ channel exception occurs:

1. We are creating a new connection even though the connection might be fine
2. We are not closing the old connection and are creating a new one

Why is the example using `Channel.NotifyClose()` this way, and is this best practice?

**Comment by michaelklishin** [comment]
Channel exceptions generally do not trigger connection recovery. Simply opening a new channel in that case is enough. So this sounds like a mistake that should be corrected. Please submit a PR?

**Comment by Raqbit** [comment]
Closed by #392
