### ISSUE TITLE
Go module `go` directive

### ISSUE THREAD

**Issue by kpurdon** [streadway/amqp#395]
Following up on #394 I wanted to track figuring out how to properly set the go directive.

An [issue](https://github.com/golang/go/issues/30791) has been filed that provides some clarity. 

Of note:

> The basic guideline is fairly simple: a "go" directive 1.N means that the code in that module is permitted to use language features that existed in 1.N even if those features were removed in later releases of the language.

So the directive is really important only after features are removed from Go in a new version. Since this is not an issue currently I _think_ we should set the directive to the current version `go 1.12`.

The only thing to note is that there was a bug in Go 1.11.0 -> 1.11.3 (fixed in 1.11.4) that prevents builds for modules with the `go 1.12` directive. I'm personally OK with that, but it's not my call.

Again, happy to open a PR, wanted to raise the issue first.

**Comment by kpurdon** [comment]
I guess to add to this the README states:

> This library supports two most recent Go release series, currently 1.10 and 1.11.

So perhaps this directive should be `go 1.11` and 1.10 support should be dropped. Then update to `go 1.12` when 1.13 is released and 1.11 is dropped, ...

**Comment by streadway** [comment]
Is a viable alternative to only add the `go 1.12` directive to the `go.mod` when version 1.14 is released and leave it empty until then?

**Comment by kpurdon** [comment]
I'd suggest just leaving it as is, and then updating to `go 1.12` when 1.13 is released and this module drops <1.12 support.
