### ISSUE TITLE
Confusing NotifyPublish() documentation

### ISSUE THREAD

**Issue by taybin** [streadway/amqp#396]
> Acknowledgments will be received in the order of delivery from the NotifyPublish channels even if the server acknowledges them out of order.

If the server acknowledges them out of order, does this mean the NotifyPublish channel won't do anything until the expected confirmations have come in?  Say we have published messages [1, 2, 3], and the server acks 2, and then 1.  Does this mean that the NotifyPublish channel won't write anything about 2 until the server acks 1, and then it will send the acks in the order 1, 2 over the channel?

My concern is that 2 could be ack'd, but then the server or client crashes and the ack for 1 isn't delivered, and then the client will have to resend message 2, even though it was successfully ack'd by the server.

**Comment by streadway** [comment]
That's correct and can also happen while the ack for msg 2 is in-flight (sent by the server but not yet received by the client).

**Comment by taybin** [comment]
Okay, thank you.
