### ISSUE TITLE
What's the best practice for publishing messages?

### ISSUE THREAD

**Issue by osenv** [streadway/amqp#400]
Hello,

Thanks for this great rabbitmq golang library. We are now using this for consuming messages only. As for publishing messages, we are now planning to switch php to golang as well by using this library.

In php, it's really simple, so to speak, we start a connection and publish a message and then close it. This is not good for rabbitmq cluster performace improvement.

Given that using this library, I'm planning to build one connection over cluster per queue, but how many channels should I use inside each connection?  If I use only one channel for QueueA, and if there are hundreds of thousands of messages to be sent simutaneously to this queue, is this solution ok?

https://github.com/streadway/amqp/blob/master/channel.go#L1328

Since there's a lock for channel, I don't think this is asynchronous message sending.

Thanks for any help in advance.

**Comment by lukebakken** [comment]
The ideal number of connections and channels per connection depends on several factors, like average message size, publishing rate, and performance of your environment.

Why not try out several different scenarios, benchmark them, and then report back here to help others? Scenarios to benchmark publishing to a single queue -

* One connection, one channel
* One connection, multiple channels
* Multiple connections, one channel each
* Multiple connections, multiple channels

My guess is you will find an ideal number of connections and channels per connection for your specific environment, with diminishing returns as the number of each increases.

**Comment by houseofcat** [comment]
@osenv I have made efforts to try and make this easier by wrapping this repo.

https://github.com/houseofcat/turbocookedrabbit

I create ConnectionPools and ChannelPools. Chiming with @lukebakken has iterated on, there is a unique performance signature of every system and you need to test what works best for you. For example, I like to have abstract connections and channels in pools, thus load balancing over the connections. My library can help you pinpoint a solid base setup if you want to use pools or just extract coding ideas.

**Comment by bombsimon** [comment]
Just to chip in (and maybe others ending up here) after seeing the comment above, I'm co-author of [0x4b53/amqp-rpc](https://github.com/0x4b53/amqp-rpc) which has a pretty extensive setup for reliability and reconnects. It uses one connection for publishing and one for subscribing with one channel per connection. Like the name is indicating it's great to use for synchronous RPC but works well with the more common asynchronous approach as well.
