### ISSUE TITLE
DialConfig does not respect Timeout

### ISSUE THREAD

**Issue by sorenvonsarvort** [streadway/amqp#411]
Currently I have an issue - my worker starts earlier then RabbitMQ server, which leads to `connection refused` error:

```go
conn, err = amqp.Dial("amqp://guest:guest@rabbitmq/")
```

```
dial tcp 172.19.0.3:5672: connect: connection refused
```

I have tried to set the timeout, but this changed exactly nothing:

```go
conn, err = amqp.DialConfig("amqp://guest:guest@rabbitmq/", amqp.Config{
	Dial: amqp.DefaultDial(time.Second * 120),
})
```

The only solution was to create a cycle and try connecting until an error happens:

```go
err := errors.New("kek")
var conn *amqp.Connection
for i := 0; err != nil; i++ {
	conn, err = amqp.Dial("amqp://guest:guest@rabbitmq/")
	fmt.Println(i, err)
}
```

This code produces the following output:

```
...
26568 dial tcp 172.19.0.3:5672: connect: connection refused
26569 dial tcp 172.19.0.3:5672: connect: connection refused
26570 dial tcp 172.19.0.3:5672: connect: connection refused
26571 <nil>
```

So, it connects usually after ~26K tries.

Why does the timeout affects nothing?

What is the best way to make it connect allowing some timeout?

**Comment by lukebakken** [comment]
You are using the correct method. As this code shows, `DialTimeout` will return immediately when a port is not accepting connections:

```
package main

import (
	"net"
	"os"
	"time"
)

func main() {
	conn, err := net.DialTimeout("tcp", "localhost:6666", 30 * time.Second)
	if err != nil {
		println("Dial failed:", err.Error())
		os.Exit(1)
	}

	conn.Close()
}
```

In your case, you should add a backoff between each connection attempt.

**Comment by sorenvonsarvort** [comment]
Thank You so much, I will close the issue
