### ISSUE TITLE
failed to dail() when password contains with special characters

### ISSUE THREAD

**Issue by ardypro** [streadway/amqp#416]
Admin configured my account and the password contains "#" and other special characters, it threw out _RabbitMQ connection failure: parse amqp://ssib:*ssib_password: invalid port ":*ssib_password" after host_ when dial() to remote server.

**Comment by lukebakken** [comment]
@ardypro please help the people who volunteer to maintain this code by providing a runnable set of code to reproduce your error. Based on your description, I can _guess_ that you're probably using an `amqp://` URI that needs to have certain elements URI-encoded, but I can't be _certain_.

If you wish to have an answer or resolution quickly, provide code that can be compiled and run that demonstrates your issue. Thank you.

**Comment by muyuren** [comment]
account := url.QueryEscape(your account )
password := url.QueryEscape(your password )

**Comment by devloper999** [comment]
Hi, Even I am facing the same issue with amqp.Dial, if the username or password has "#" symbol, then the split happen at # internally in the Dial code. Can someone please help how to resolve this. I tried even query escape but no luck. 
Code inside amqp Dial method : url.Parse splits at # and it is causing the invalidPort error.
func Parse(rawURL string) (*URL, error) {
	// Cut off #frag
	u, frag := split(rawURL, '#', true)


Below is the code snippet
func connectToRMQServer() {
    fmt.Println("Connection staretd ")
    rmqurl := "amqp://guest:" + url.QueryEscape("guest#") + "@localhost:5672/"
    fmt.Println("rmqurl ", rmqurl)
    conn, err := amqp.Dial(rmqurl)
    if err != nil {
        fmt.Println("Error is ", "Failed to connect to RabbitMQ", err)
        return
    }
    fmt.Println("Connection succesful ", conn)
}
func main() {
    fmt.Println("in main")
    connectToRMQServer()
}

**Comment by lukebakken** [comment]
What is printed by this code???

```
fmt.Println("rmqurl ", rmqurl)
```

**Comment by devloper999** [comment]
just wanted to check how the url looks before sending it to dial so I am printing

**Comment by lukebakken** [comment]
No, I mean, what is actually printed. Run your code and paste the output in your response.

**Comment by devloper999** [comment]
rmqurl  amqp://guest:guest#@localhost:5672/
Error is  Failed to connect to RabbitMQ parse "amqp://guest:guest": invalid port ":guest" after host

I think adding url.QueryEscape worked :
rmqurl  amqp://guest:guest%23@localhost:5672/
connection is  &{*******VMware, Inc. or its affiliates. information:Licensed under the MPL 2.0. Website: https://rabbitmq.com platform:Erlang/OTP 24.2 product:RabbitMQ version:3.9.12] [en_US] 0}

Thanks!!

**Comment by Chopra-Deven** [comment]
I am still facing this issue here the code snippet @devloper999 @lukebakken 
-------------------------------------------------------------------------------------------------


user := "admin"
password := url.QueryEscape("Kind@123")
ip := "192.192.10.10" (assume I used valid IP)
port := 15672 (assume I used valid port)


rmqurl := fmt.Sprintf("amqp://%s:%s@%s:%d/", user, password, ip, port)

conn, err := amqp.Dial(rmqurl)

---------------------------------------------------------------------------------------------------------
rmqurl : amqp://admin:Kind%40123@192.192.10.10:15672/


I am getting this error : 

Exception (501) Reason :  "EOF"
