### ISSUE TITLE
RabbitMQ 3.7.17: error "frame could not be parsed"

### ISSUE THREAD

**Issue by lmtg** [streadway/amqp#420]
Hi,

I'm using golang 1.11 and recently upgraded my RabbitMQ server from 3.6.6 to 3.7.17 and now I get this error:
```
Unable to connect to RabbitMQ server: Exception (501) Reason: "Exception (501) Reason: \"frame could not be parsed\""
```
Even this example (https://www.rabbitmq.com/tutorials/tutorial-three-go.html) doesn't work anymore... same error.

Those anyone else have this issue ?

Thanks
Leandro

**Comment by lmtg** [comment]
sorry this problem was due to a sysadmin misconfiguration issue.

**Comment by netaskd** [comment]
The problem appears when RMQ connection is not properly set.
For example, a client tries to connect plainext (amqp) to tls (amqps) server or vise versa.
