### ISSUE TITLE
Request - Max Tries

### ISSUE THREAD

**Issue by cansozeri** [streadway/amqp#422]
Hi,

Is there anyway to add max retry functionality like Laravel --tries=3 ?

I think every reject action, consumer can add a property if not exist to the message like "attempts_count" = 1 and if exists, increment like "attempts_count" = 2. This functionality will be great and can implement on Delivery - Reject and Nack ??

**Comment by dumindu** [comment]
Or at least better having a proper interface to access the values of `delivery.Headers["x-death"]`.

**Comment by rizalgowandy** [comment]
:up: this is a good thing to have on the client.
Go-client is falling behind other language clients.

**Comment by michaelklishin** [comment]
Quorum queues keep track of redelivery counts. The counter is also exposed using headers. Clients cannot accurately track redeliveries since they by definition will involve every active consumer. RabbitMQ nodes, however, can and for quorum queues, do.
