### ISSUE TITLE
amqp installed but not loaded with php7.4

### ISSUE THREAD

**Issue by easternmayurt** [streadway/amqp#433]
I have installed amqp 1.9.4 with php7.4, it shows in phpinfo(), but when I am trying to use it its not loaded ``` extension_load('amqp'); ```  this return false to me, can anyone help me in this.

**Comment by bombsimon** [comment]
This project is for the Go client, you probably want to create your issue in [pdezwart/php-amqp](https://github.com/pdezwart/php-amqp).

**Comment by easternmayurt** [comment]
Ok @bombsimon I will remove this from here and raise it in the above mentioned repo.
