### ISSUE TITLE
Publishing to an exchange that does not exist

### ISSUE THREAD

**Issue by rebbuh** [streadway/amqp#449]
When a message is published to an exchange that does not exist, the [Publish](https://github.com/streadway/amqp/blob/master/channel.go#L1326) method does not return an error.
Is there any way to handle this situation?

I know that I can use [NotifyReturn](https://github.com/streadway/amqp/blob/master/channel.go#L515) to get a [Return](https://github.com/streadway/amqp/blob/master/return.go#L15) struct when the _mandatory_ flag is set and there is no route for the given routing key, but obviously this does not apply to non-existing exchanges.

This somehow relates to issue #445, but it was closed by @BentCoder shortly after its creation without any comment.

**Comment by BentCoder** [comment]
http://www.inanzzz.com/index.php/post/0aeg/creating-a-rabbitmq-producer-example-with-golang

There is a "confirmation mode" section in post above. It addresses your issue. The "create.go" file uses it. Also read the whole post. It explains many things.

**Comment by rebbuh** [comment]
Thanks!
The important part is to also subscribe to [channel.NotifyClose](https://github.com/streadway/amqp/blob/master/channel.go#L447), not only to [connection.NotifyClose](https://github.com/streadway/amqp/blob/master/connection.go#L272).
