### ISSUE TITLE
basicQos only works before basicConsume is invoked?  Needs clarification in docs?

### ISSUE THREAD

**Issue by scodesmse** [streadway/amqp#461]
Hi.

This post is follow-up of sorts to another guy's post 3 years ago ( [https://github.com/streadway/amqp/issues/236](https://github.com/streadway/amqp/issues/236) ).  He asks about basicQos after basicConsume and was directed to the documentation, but the documentation doesn't indicate that basicQos is, apparently, silently ignored after basicConsume is active.

I do note, however, that in all the doc examples, basicQos is called before basicConsume.

FWIW, I'm using the java client.

**Comment by michaelklishin** [comment]
I’m not sure why you are bringing this up here if you use the Java client. In any case, [RabbitMQ doc guide on confirms](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch) and another one on [Consumer prefetch](https://www.rabbitmq.com/consumer-prefetch.html) do mention this. They also mention how the “global” flag (PSA: it will be a no-op in a future RabbitMQ release, so I’m only mentioning it for completeness’ sake) alters `basic.qos` behavior in a way that seems relevant here.

This is open source software, so you are welcome to contribute a PR that mentions that `basic.qos` won’t have any effect on existing consumers.

**Comment by michaelklishin** [comment]
I am even more confused now because my response in #236 does refer to the RabbitMQ doc guides, not any particular doc comment specific to this client library. In any case, a PR for the Java client that perhaps updates `Channel#basicQos` JavaDoc would be considered.
