### ISSUE TITLE
Policy option

### ISSUE THREAD

**Issue by BentCoder** [streadway/amqp#469]
Hi,

Is there a way for us to set a policy on a queue? For example `ha-mode: all`

Thanks

**Comment by bombsimon** [comment]
According to [this SO post](https://stackoverflow.com/a/19162149/2274551) policies cannot be set over the AMQP protocol and is thus not a part of this project. How to set policies via the RESTful API is described in the [RabbtMQ documentation](https://www.rabbitmq.com/parameters.html#policies). This should be possible with `net/http`.
