### ISSUE TITLE
does it support sending multiple messages in one publishing 

### ISSUE THREAD

**Issue by liuchizhen** [streadway/amqp#474]
I did a test about RabbitMQ's publish rate with streadway/amqp，and the date is confused me:
| the number of messages |  publish rate |
| ----------- | ----------- |
|    5,000     |   1,000/s    |
|  10,000     |   2,000/s    |
|  15,000     |   3,000/s    |
|  18,000     |   3,600/s    |
|  19,000     |   3,800/s    |
|  20,000     |    4,000/s   |
So I captured packets using wireshark, and found every publishing only sends one AMPQ packet. I think this is why publish rate is lower and it affects the speed of consumption.

does streadway/amqp can send multiple AMPQ packets in one publishing?
![rabbitmq](https://user-images.githubusercontent.com/34055482/93858393-afcbb380-fcee-11ea-85a3-ce346ee3cc40.png)

**Comment by michaelklishin** [comment]
There is no such operation in any of the protocols GA versions of RabbitMQ support, including AMQP 0-9-1 implemented by this client.

**Comment by liuchizhen** [comment]
Then, how do I batch messages like this using streadway/amqp?

![rabbitmq_perfTest](https://user-images.githubusercontent.com/34055482/94090132-7195d780-fe47-11ea-9b95-0cb94a4735dd.png)
