### ISSUE TITLE
Is there a plan to enable RabbitMQ Stream API?

### ISSUE THREAD

**Issue by avamingli** [streadway/amqp#481]
Since the RabbitMQ will enable Stream API in next Release 3.9 (master already has this feature), is there a plan to enable Stream API in this repo?

**Comment by kjnilsson** [comment]
I can't answer for the maintainers of this client of course but we (RabbitMQ team) generally expect streams to have separate dedicated clients as it a completely separate protocol.

**Comment by michaelklishin** [comment]
Not as part of this client library. It should be a separate RabbitMQ stream protocol client in Go.
