### ISSUE TITLE
TestTLSHandshake failing with Go 1.18 due to denial of SHA1 certificates

### ISSUE THREAD

**Issue by GlenPickle** [streadway/amqp#523]
Per the Go 1.18 release notes: "crypto/x509 will now reject certificates signed with the SHA-1 hash function. This doesn't apply to self-signed root certificates. Practical attacks against SHA-1 [have been demonstrated since 2017](https://shattered.io/) and publicly trusted Certificate Authorities have not issued SHA-1 certificates since 2015."

This is causing the test "TestTLSHandshake" to fail with Go 1.18

**Comment by michaelklishin** [comment]
This project has moved to https://github.com/rabbitmq/amqp091-go.

Please submit a PR if you understand the issue in enough detail. Thank you.
