### ISSUE TITLE
Timeout on Dial

### ISSUE THREAD

**Issue by JohnMurray** [streadway/amqp#72]
Hello,

This is probably somehow my fault, but I was looking at your example and I tried to get it running for and existing RabbitMQ server. I have been consuming from this service using Python and Pika without issue with code as simple as:

``` python
connection = pika.BlockingConnection(
    pika.ConnectionParameters('rabbitmq.sand.lax1'))
channel = connection.channel()
channel.queue_declare(queue = 'my-queue-name')
channel.queue_bind(exchange = 'my-exchange-name',
                   queue = 'my-queue-name',
                   routing_key = 'my-routing-key')

channel.basic_consume(some_callback_func, queue = 'my-queue-name')
channel.start_consuming()
```

I can assume that with such a simple connection setup, that I am connecting with the default settings (which the server is configured to use) plus the defined host (I have verified this by viewing existing connections in the Management Console):
- username: `guest`
- password: `guest`
- host: `rabbitmq.sand.lax1`
- port: `5672`
- virtual host: `/`
- protocol: `amqp`

I have tried to use the simple-example in the repo to connect given these parameters (filling in the queue/exchange details as well) but I get a timeout on Dial every time. I have confirmed that the host is reachable and the port is open and the Pika code can connect from the same machine. I am connecting with the uri `amqp://guest:guest@rabbitmq.sand.lax1:5672/`. I'm not sure if there is something that I am missing that is library-specific or what.

Any help with this is greatly appreciated and I apologize in advance if this is just some stupid mistake on my part, but I just can't figure out why the Pika client can connect and the go-client can't.

**Comment by michaeljs1990** [comment]
Wow, this is interesting. Just spend ~2 hours trying to figure out a ton of random errors i was running into. Switch to using IP after reading this and everything works perfect. I would be curious as to what is causing this. I am using 1.4.1 on OSX 10.10.2 and installed go with brew.

**Comment by JohnMurray** [comment]
@michaeljs1990 My particular problem was that I was running Go on a Linux kernel version that was not supported (too old). I would imagine Mac support is pretty good, but perhaps 10.10 introduced changes that are affecting the way Go works? Perhaps re-compiling Go from source would root out your issues.
